### ISSUE TITLE
Publish documentation is for newest master instead of the latest release

### ISSUE THREAD

**Issue by maciejkula** [jgallagher/rusqlite#102]
This leads to a confusing couple of minutes when rust cannot import `rusqlite::Connection`, because of the rename in https://github.com/jgallagher/rusqlite/commit/4327a84edb2773ef740891efad8ec11e38d3b774

It might help to keep your docs in line with your latest version on crates.io instead of your master.

**Comment by jgallagher** [comment]
Whoops! Thanks for the report. I manually rolled them back to the docs for 0.5.0, and #103 should prevent this from happening again.

**Comment by maciejkula** [comment]
Amazing, thanks a lot!

It would be great if cargo doc had a concept of a version.
