### ISSUE TITLE
No docs for features

### ISSUE THREAD

**Issue by Dashed** [jgallagher/rusqlite#111]
@jgallagher 

There doesn't seem to be docs for extra features of rusqlite `v0.6`. e.g. http://jgallagher.github.io/rusqlite/rusqlite/index.html?search=backup

I had to rely on source comments. Is this intended?

**Comment by jgallagher** [comment]
Nope, definitely not. Just an oversight in having to copy-paste features into the script I use for publishing them. It's fixed; hopefully in the future rust-lang/cargo#1173 is available and we can drop `--all-features` into the script instead.

**Comment by Dashed** [comment]
Awesome. Thanks! :+1:
