### ISSUE TITLE
Non-idiomatic constructor

### ISSUE THREAD

**Issue by marcusklaas** [jgallagher/rusqlite#13]
Firstly, please me tell me if I'm intruding on your project too much!

I was thinking the constructor for `SqliteConnection` could be made more idiomatic by passing it a `&Path` instead of a `&str`. An added benefit would be that non-utf8 file paths could be opened as well.

A different constructor would have to be added for an in-memory connection.

What do you think?

**Comment by jgallagher** [comment]
I think you're right. It looks like `std::path` is currently being reworked (https://github.com/rust-lang/rust/issues/20034, https://github.com/rust-lang/rfcs/pull/474#issuecomment-68608439). If you want to do the work to make the changes for the current `std::path`, I won't stop you. :) If not (and I don't, personally), we can leave this issue open and make this change when `std::path` is reformed.

**Comment by jgallagher** [comment]
Oh, and I'm definitely not feeling intruded upon. Glad to see someone using this!

**Comment by jgallagher** [comment]
@marcusklaas How does #19 look? Path reform landed a couple days ago.

**Comment by marcusklaas** [comment]
Good stuff!
