### ISSUE TITLE
How to open a shared, in-memory database?

### ISSUE THREAD

**Issue by euclio** [jgallagher/rusqlite#135]
I've tried

```rust
Connection::open_in_memory_with_flags(SQLITE_OPEN_SHARED_CACHE).unwrap()
```
```rust
Connection::open_with_flags(":memory:?cache=shared", SQLITE_OPEN_URI).unwrap()
```

Both fail with `APIMisuse`.

**Comment by jgallagher** [comment]
This is a little tricky for two reasons. From the [docs on sqlite3_open_v2](https://www.sqlite.org/c3ref/open.html):

* You must always pass one of `SQLITE_OPEN_READONLY`, `SQLITE_OPEN_READWRITE`, or `SQLITE_OPEN_READWRITE|SQLITE_OPEN_CREATE` as the flags to open (optionally with other bits or'd in). This is why you're getting API misuses - shared_cache / open_uri by themselves aren't allowed.
* For in-memory databases [shared cache](https://www.sqlite.org/sharedcache.html) databases specifically:

    > Beginning with SQLite version 3.7.13, shared cache can be used on in-memory databases, provided that the database is created using a URI filename. For backwards compatibility, shared cache is always disable for in-memory databases if the unadorned name ":memory:" is used to open the database.

Using `open_in_memory_with_flags` uses the unadorned name ":memory:", so adding a `SQLITE_OPEN_SHARED_CACHE` flag to that call will essentially be ignored by SQLite. This should work, however, assuming SQLite no older than 3.7.13:

```rust
Connection::open_with_flags("file::memory:?cache=shared", SQLITE_OPEN_URI | SQLITE_OPEN_READ_WRITE)
```
