### ISSUE TITLE
Fix handling of SQLite column types

### ISSUE THREAD

**Issue by jgallagher** [jgallagher/rusqlite#160]
Experimenting with possibilities brought up on #158, I realized we're leaving open the possibility of using `sqlite3_column_type` incorrect. From [SQLite's docs](https://www.sqlite.org/c3ref/column_blob.html):

> The value returned by sqlite3_column_type() is only meaningful if no type conversions have occurred as described below. After a type conversion, the value returned by sqlite3_column_type() is undefined. Future versions of SQLite may change the behavior of sqlite3_column_type() following a type conversion.

We call `sqlite3_column_type` several places, including many `column_has_valid_sqlite_type` implementations and the `FromSql` impls for `Option<T>` and `Value`. If the user performs an operation that requires SQLite type conversion prior to these being called, we're hitting undefined behavior.

At first I thought maybe we could avoid calling `sqlite3_column_type` altogether, and allow `get`s that hit incorrectly-typed data to fall back onto SQLite's type conversions (which are well defined for all of SQLite's types). That could get rid of `column_has_valid_sqlite_type`, but we still need a way to implement `Option<T>` and `Value`.

The only way I can think of to do this correctly is to call `sqlite3_column_type` ahead of time for each column. This could be cached in the construction of the `Rows` handle, but not up in `Statement` (since a DDL execution between statement queries could result in changes).

@gwenn Any thoughts on this? Is my understanding of this issue correct, and if so, can you think of any other solution? I checked a couple of other SQLite wrappers; go-sqlite3 pulls out all the column values ahead of time during iteration (it calls `sqlite3_column_type` but always as the first operation for a column), and [sqlite-jdbc](https://bitbucket.org/xerial/sqlite-jdbc/src/8de652d3f54cdfd32d5a493130c995f36e16c652/src/main/java/org/sqlite/RS.java?at=default&fileviewer=file-view-default) appears to have the same issue we currently do.

**Comment by gwenn** [comment]
`sqlite3_column_type` for one column in one row can be called many times even after calling `sqlite3_column_int/double/text/blob` if no conversion happens (for exemple `sqlite_column_int` called when the type is `SQLITE_INTEGER`).
And it seems to me that `rusqlite` does not use/do any conversion (by calling one `sqlite3_column_int/double/text/blob` that does not match the type returned by `sqlite3_column_type`).
So, for me, `rusqlite` is ok.

And, SQLite uses dynamic type (each cell has its own type): http://sqlite.org/datatype3.html.
So, please, don't try to cache the datatype in the `Rows` or use [`sqlite3_column_decltype`](http://sqlite.org/c3ref/column_decltype.html).

**Comment by jgallagher** [comment]
> And, SQLite uses dynamic type (each cell has its own type): http://sqlite.org/datatype3.html.
So, please, don't try to cache the datatype in the Rows or use sqlite3_column_decltype.

You're right! We'd have to cache them in `Row` itself. :(

> And it seems to me that rusqlite does not use/do any conversion (by calling one sqlite3_column_int/double/text/blob that does not match the type returned by sqlite3_column_type).

I think that's true for `rusqlite` itself, but it's not enforced if someone defines their own `FromSql` implementation that performs type conversion and then later calls a different method that will call `sqlite3_column_type`. `rusqlite`'s current design sort of disables SQLite's dynamic typing (by performing column type checks and erroring if they don't match instead of letting SQLite do type conversion). I guess there are at least two possible paths forward:

* Rework `FromSql` so that you _can't_ cause a type conversion. This would be the closest to how rusqlite currently works.
* Cache the type in `Row` and allow people to ask what the type was but still use SQLite's type conversions if they wanted to. This would essentially remove some checks from rusqlite, making it less in the spirit of Rust but more in the spirit of SQLite.

I'm really not sure which way to go on this. I'm inclined to do the former because this is a Rust wrapper and Rust programmers _probably_ favor more type checks rather than less, but it does disable some of SQLite's functionality.

**Comment by jgallagher** [comment]
I guess you can always get SQLite type conversions back by using an explicit [`CAST (value AS type)`](https://www.sqlite.org/lang_expr.html) in your query. That's an argument for keeping all our type checks and making sure you can't bypass them with a safer `FromSql`.

**Comment by jgallagher** [comment]
Pushed up a branch experimenting with a possible reimplementation of `FromSql`: https://github.com/jgallagher/rusqlite/compare/safe-fromsql

High-level summary: Added a new `BorrowedValue` enum:

```rust
pub enum BorrowedValue<'a> {
    Null,
    Integer(i64),
    Real(f64),
    Text(&'a str),
    Blob(&'a [u8]),
}
```

It has helper methods like `as_str() -> Result<&str>` to remove the need to `match` if you only support one of the cases. `FromSql` is redefined to take one of these instead of FFI interfaces:

```rust
pub trait FromSql: Sized {
    fn column_result(value: BorrowedValue) -> Result<Self>;
}
```

This _greatly_ simplifies implementing `FromSql` as you can see in the diff. We call `sqlite3_column_type` in constructing the `BorrowedValue`, and by not giving clients access to the raw statement, we prevent them from causing a type conversion.

What do you think? @scottlamb if you want to take a look at that diff too, I'm curious what you think. For your UUID use case it'd still require a wrapper type, so I think there's still an argument for zero-copy borrowing the str/blob. But I think it'd be easier to get to that from this safer `FromSql` than where we are today.

**Comment by scottlamb** [comment]
I agree that's a much more pleasant `FromSql` interface. Yes, I still think I'd prefer having the ability to borrow the blob/str without creating a wrapper type.

**Comment by jgallagher** [comment]
Full PR is open. Realized we can also drop `functions::FromValue` with this change, which is great too.
