### ISSUE TITLE
Redesign ToSql to be implementable without `unsafe`

### ISSUE THREAD

**Issue by jgallagher** [jgallagher/rusqlite#162]
After merging #161 or something like it, it'd be great to make `ToSql` safe too. The easiest definition would be something like:

``` rust
trait ToSql {
    fn sqlite_value(&self) -> Result<Value>;
}

// for example...
impl<'a> ToSql for &'a str {
    fn sqlite_value(&self) -> Result<Value> {
        Ok(Value::Text(self.to_string()))
    }
}
```

but it'd be nice to avoid forcing an extra copy (like in the hypothetical `str` impl above) since SQLite is going to turn around and make its own copy too. I don't think this is possible:

``` rust
trait ToSql {
    fn sqlite_value<'a>(&'a self) -> Result<BorrowedValue<'a>>;
}
```

since there may be types which can't return a reference into themselves (e.g., if they have to serialize themselves into a string). I'm open to ideas here, both for the interface and the name of the method. A couple of possibilities:
- Define an enum allowing implementors to choose between `Value` and `BorrowedValue`:

``` rust
enum ToSqlOutput<'a> {
    case Owned(Value)
    case Borrowed(BorrowedValue<'a>)
}

trait ToSql {
    fn sqlite_value<'a>(&'a self) -> Result<ToSqlOutput<'a>>;
}
```
- Pass in a closure that implementors must call. We'd check and panic at runtime if they don't call it?

``` rust
trait ToSql {
    fn sqlite_value<'a, F: FnOnce(Result<BorrowedValue<'a>>)>(&'a self, output: F);
}
```

@gwenn What do you think?

**Comment by gwenn** [comment]
There is one thing that can greatly reduce copy but not currently supported by `rusqlite` is binding reuse:
```C
sqlite3 *db = NULL;
sqlite3_stmt *stmt = NULL;
int rc = 0;
rc = sqlite3_open_v2(":memory:", &db, SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE, NULL);
if (db == NULL || SQLITE_OK != rc) {
    fprintf(stderr, "Error: unable to open database: %s\n", sqlite3_errmsg(db));
    exit(1);
}

rc = sqlite3_prepare_v2(db, "SELECT ?", -1, &stmt, NULL);
if (stmt == NULL || SQLITE_OK != rc) {
    fprintf(stderr, "Error: prepare stmt: %s\n", sqlite3_errmsg(db));
    exit(1);
}
// Bind once
rc = sqlite3_bind_int(stmt, 1, 1);
if (SQLITE_OK != rc) {
    fprintf(stderr, "Error: bind param: %s\n", sqlite3_errmsg(db));
    exit(1);
}
// Reuse many times...
for (int i = 0; i < 10; i++) {
    rc = sqlite3_step(stmt);
    if (SQLITE_OK != rc && SQLITE_DONE != rc && SQLITE_ROW != rc) {
        fprintf(stderr, "Error: %s\n", sqlite3_errmsg(db));
        exit(1);
    }
    sqlite3_reset(stmt);
}
sqlite3_finalize(stmt);
sqlite3_close(db);
```

It seems difficult to make binding reusable when the data is borrowed...

**Comment by jgallagher** [comment]
Ahh, yeah, that's interesting. I don't think it affects the `ToSql` trait, since that's used in the "binding" step. Getting this reuse would require a different way of calling query/execute. Something like `query_with_previous_parameters`? I don't think borrowed data is a concern with this since SQLite makes its own copy when you bind, right?

**Comment by gwenn** [comment]
> SQLite makes its own copy when you bind

only when `SQLITE_TRANSIENT` is specified.

**Comment by jgallagher** [comment]
True, but we always specify it. :-)

So there are at least two things we could do:

* (Easy, I think) Add ability to reuse bound parameters. Maybe `Statement` gets a method like `bind_parameters(&[&ToSql]) -> BoundStatement`, and `BoundStatement` has all the `query...` methods but they don't need params.
* (Hard, I think) Add ability to bind text/blobs without `SQLITE_TRANSIENT`.

The first one is orthogonal to a new `ToSql` interface. The second definitely isn't, but I don't have any ideas off the top of my head how we could allow that safely.

**Comment by gwenn** [comment]
At least, we can use `SQLITE_STATIC` with `sqlite3_bind_text` when the text is empty ("").
And we can use `sqlite3_bind_zeroblob` instead of `sqlite3_bind_blob` when the byte slice is empty.

**Comment by jgallagher** [comment]
True - both of those can be done internally. I'm not sure what the lifetimes on a variant of `prepare(&[&ToSql])` would look like if we wanted to tie them to the lifetime of the returned statement, or if it's even possible to express that. I wonder if we could use borrowed data more easily for the one-shot functions like `Connection::execute` and `Connection::query_row`.
