### ISSUE TITLE
Database not closed when statements are cached

### ISSUE THREAD

**Issue by maltek** [jgallagher/rusqlite#186]
Closing database connections fails when prepared statements are cached. Setting `set_prepared_statement_cache_capacity` to `0` before closing seems to work as a workaround, but I haven't dug into the code to see if doing so in the `close()` (and `drop()`) implementation would be a good idea.

```
#[cfg(test)]
mod tests {
    extern crate rusqlite;
    use tests::rusqlite::Connection;

    #[test]
    fn it_works() {
        let conn = Connection::open_in_memory().unwrap();
        conn.prepare_cached("SELECT * FROM sqlite_master;").unwrap();

        conn.close().expect("connection not closed");
    }
}
```

**Comment by gwenn** [comment]
Indeed,
The cache must be flushed before closing the connection !
I will try to fix and send a PR this week-end.

**Comment by gwenn** [comment]
Another solution (not tested yet) will be the replacement of `sqlite3_close` by `[sqlite3_close_v2](http://sqlite.org/c3ref/close.html)`:
> If sqlite3_close_v2() is called on a database connection that still has outstanding prepared statements, BLOB handles, and/or sqlite3_backup objects then it returns SQLITE_OK and the deallocation of resources is deferred until all prepared statements, BLOB handles, and sqlite3_backup objects are also destroyed.
When the Rust connection is dropped, the cache is dropped as well as the cached prepared statements...
