### ISSUE TITLE
Foreign key support

### ISSUE THREAD

**Issue by freiguy1** [jgallagher/rusqlite#192]
Hello there. I was writing a little program and as I was writing some tests, I wanted to see if I would see an error when I delete items from a table which are referenced by foreign key in another table.  

So I have table A, and table B.  B has a foreign key reference to A.  There are items in A and B.  I deleted all items in A and was expecting to see a foreign key constraint error.  There wasn't any error, and when I looked at table B using `sqlite3`, it had many items referencing rows from table A which didn't exist.

Do I need to enable some switch to have foreign key constraints work?

Thanks!

**Comment by gwenn** [comment]
You need to set this [pragma](http://sqlite.org/pragma.html#pragma_foreign_keys).
Something like:
```rust
conn.execute("PRAGMA foreign_keys = ?1", &[1]).unwrap();
```
Or there is also this unsafe [method](http://sqlite.org/c3ref/db_config.html):
```rust
unsafe {
    ffi ::sqlite3_db_config(conn.handle(), SQLITE_DBCONFIG_ENABLE_FKEY, 1, ptr::null_mut());
}
```
Regards.

**Comment by freiguy1** [comment]
Thanks @gwenn, that did it for my unit tests, and it worked!  My next question: I'm using r2d2 and nickel-sqlite.  When I get a connection from the pool, do I need to run this `PRAGMA` command every time, or just once during the initialization of my app? This may not be the best place to ask, but I thought I would since I had this issue.

**Comment by gwenn** [comment]
The `sqlite2_db_config` doc is explicit:
> the changes apply to a single database connection (specified in the first argument)
So yes, every time you get a connection, you need to run this pragma.

Maybe you should ask that `r2d2-sqlite` supports something like a [connectionInitSql](https://github.com/brettwooldridge/HikariCP#initialization)?

**Comment by jgallagher** [comment]
It looks like `r2d2-sqlite` already supports specifying a basic [connection configuration](http://ivanceras.github.io/r2d2-sqlite/src/r2d2_sqlite/src/lib.rs.html#92-97). Maybe it could add an option for setting this pragma, or maybe we could add an open flag that we would check for and send the pragma (instead of passing it through to SQLite like we do all the existing open flags)?

**Comment by freiguy1** [comment]
To get me up and running, I created another extension for a Nickel Request for getting a db conn:

```rust
pub trait SqliteRequestExtensions {
    fn db_conn(&self) -> Result<PooledConnection<SqliteConnectionManager>, StatusCode>;
}

impl<'a, 'b, D> SqliteRequestExtensions for Request<'a, 'b, D> {
    fn db_conn(&self) -> Result<PooledConnection<SqliteConnectionManager>, StatusCode> {
        let conn = match NickelExtensions::db_conn(self) {
            Ok(c) => c,
            Err(_) => return Err(StatusCode::InternalServerError)
        };
        if let Err(_) = conn.execute("PRAGMA foreign_keys = ON", &[]) {
            return Err(StatusCode::InternalServerError);
        }
        Ok(conn)
    }
}
```

Now I use this every time instead of nickel_sqlite's `db_conn()` method.

**Comment by jgallagher** [comment]
Nice! I think you could shorten that a bit if you want:

```rust
impl<'a, 'b, D> SqliteRequestExtensions for Request<'a, 'b, D> {
    fn db_conn(&self) -> Result<PooledConnection<SqliteConnectionManager>, StatusCode> {
        NickelExtensions::db_conn(self)
            .and_then(|conn| {
                conn.execute("PRAGMA foreign_keys = ON", &[])?;
                Ok(conn)
            })
            .map_err(|_| StatusCode::InternalServerError)
    }
}
```

I'm going to go ahead and close this; I'm not a huge fan of us putting support for this into our open flags when SQLite doesn't.

**Comment by jgallagher** [comment]
Oops, the above assumes the `Result` returned by `NickelExtensions::db_conn(self)` has the same error type as `conn.execute`. If that's not true you might need two `map_err`s (this seems gross but I'm not seeing a simpler way):

```rust
impl<'a, 'b, D> SqliteRequestExtensions for Request<'a, 'b, D> {
    fn db_conn(&self) -> Result<PooledConnection<SqliteConnectionManager>, StatusCode> {
        NickelExtensions::db_conn(self)
            .map_err(|_| StatusCode::InternalServerError)
            .and_then(|conn| {
                conn.execute("PRAGMA foreign_keys = ON", &[])
                    .map_err(|_| StatusCode::InternalServerError)?;
                Ok(conn)
            })
    }
}
```
