### ISSUE TITLE
Can't close database properly when database is locked.

### ISSUE THREAD

**Issue by joshhansen** [jgallagher/rusqlite#199]
Because `Connection::close` consumes the connection, it's impossible to retry when closing yields an error. I've encountered an "Error code 5: The database file is locked" error when closing. It seems that the proper thing to do is to sleep for some time and then try again, but I can't do this because I no longer own the connection or hold a reference to it.

Very possible I'm misunderstanding something here, but from what I can understand it seems there's something wrong here.

**Comment by jgallagher** [comment]
Hmm you're right. Maybe we should return something like `std::Result<(), (Connection, Error)>` so on failure you get back both the error and the connection so you can retry. Would that be suitable for your use?

**Comment by gwenn** [comment]
Depending on the crate version, the issue may be related to #186.
Regards.

**Comment by jgallagher** [comment]
Yes, good point. @joshhansen were you using cached statements and if so, could you retry with release 0.8?

Conceptually this is still an issue though - we shouldn't consume the connection on `close()` and then fail and leave the user without a way to retry.

**Comment by jgallagher** [comment]
@joshhansen #200 addresses the API issue of `close` consuming the connection even when it fails, although I _think_ in principle you shouldn't be able to get a database locked error when closing (unless it's the result of a bug, like the prepared statement one referenced above). If you're still seeing errors from `close` on 0.8 please open another issue so we can investigate.

**Comment by joshhansen** [comment]
Yes, I am using cached statements, so the connection to #186 seems accurate. I was using 0.7.3 and tried upgrading to 0.8.0, and it appears to have resolved the error I was getting. As far as the conceptual issue with the API, I agree that returning `std::Result<(), (Connection, Error)>` would be sufficient as it would allow for arbitrary retries.

Thanks for the speedy feedback and for the library!

**Comment by jgallagher** [comment]
Cool, I won't worry about rushing out another release with #200 included then. Thanks for the update!
