### ISSUE TITLE
Potential for Unification with other sqlite libraries

### ISSUE THREAD

**Issue by theduke** [jgallagher/rusqlite#201]
@jgallagher 

I've noticed that there are multiple SQLite libraries with quite similar approaches and active commits.

Maybe you could join a discussion for potential joining of efforts here: https://users.rust-lang.org/t/sqlite-libraries-potential-for-unification/8702

In https://github.com/dckc/rust-sqlite3 , potentially retiring the bindings in favor of rusqlite was already discussed here: https://github.com/dckc/rust-sqlite3/issues/46 , maybe that can be moved along in some mutual discussion...

**Comment by jgallagher** [comment]
Thanks! I chimed in there.
