### ISSUE TITLE
Exporting libsqlite3_sys::error::ErrorCode

### ISSUE THREAD

**Issue by ErickHdez96** [jgallagher/rusqlite#218]
I'm trying to do some error handling, but I found that SqliteFailure returns an Error of tipe `libsqlite3_sys::error::ErrorCode` and I can't compare the error code returned by it, I could use the extended_code that it returns, but I think it would be better comparing to the exact error code, and not a number.

**Comment by jgallagher** [comment]
Thanks, this is in master as of #222 and will be in the next release.

**Comment by njaard** [comment]
This fix is unusable:

{{{
40 |         rusqlite::ErrorCode::DatabaseBusy, _
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `libsqlite3_sys::error::Error`, found enum `storage::rusqlite::ErrorCode`
   |
   = note: expected type `libsqlite3_sys::error::Error`
              found type `storage::rusqlite::ErrorCode`
}}}

While `ffi::ErrorCode` *is* exported, the API doesn't use that type.
