### ISSUE TITLE
Expose limits, such as SQLITE_MAX_VARIABLE_NUMBER

### ISSUE THREAD

**Issue by rnewman** [jgallagher/rusqlite#220]
SQLite includes a bunch of compile-time limits that are the backbone of the runtime limits:

https://www.sqlite.org/c3ref/c_limit_attached.html#sqlitelimitvariablenumber

The runtime limits can be retrieved via `sqlite3_limit` (though I don't see the constants passed through in the bindings?).

The compile-time limits are [nowhere to be seen](https://github.com/jgallagher/rusqlite/search?utf8=%E2%9C%93&q=SQLITE_MAX_VARIABLE_NUMBER). Can we expose a wrapper for these? Apparently the values [vary widely, from 999 as the source default to 500,000 on macOS](http://sqlite.1065341.n5.nabble.com/SQLITE-MAX-VARIABLE-NUMBER-td43457.html).

These limits are commonly used to implement chunked passing of a large number of parameters to a query, where the number of parameters might be more than 999.

**Comment by jgallagher** [comment]
Just to clarify - by "compile-time limits", you mean the `#define`'d constants that you pass to `sqlite3_limit`, right? Does #221 address this?

**Comment by rnewman** [comment]
#221 supplies the constants and wrapper function to do dynamic limit checking — fetching the current variable limit with `sqlite3_limit(SQLITE_LIMIT_VARIABLE_NUMBER)`, for example.

Unless the limit has otherwise been changed, that function call will return the value of the compile time preprocessor macro `SQLITE_MAX_VARIABLE_NUMBER`. If it has been changed, `sqlite3_limit` will return the current value.

Each limit cannot be increased above that defined constant (`SQLITE_MAX_VARIABLE_NUMBER` in this particular case), so knowing the constant itself can be useful.

Ideally those maxes themselves would also be available to Rust code, just as they are when compiling against `sqlite3.h`. #221 doesn't address that, but it's certainly much better than nothing!

**Comment by jgallagher** [comment]
Are those available in `sqlite3.h`? I'm not seeing anything related to them in mine (3.16.2):

```
[2713 john@Johns-MacBook-Pro sqlite/3.16.2/include]% ls
sqlite3.h     sqlite3ext.h
[2714 john@Johns-MacBook-Pro sqlite/3.16.2/include]% grep VARIABLE *
sqlite3.h:** [[SQLITE_LIMIT_VARIABLE_NUMBER]]
sqlite3.h:** ^(<dt>SQLITE_LIMIT_VARIABLE_NUMBER</dt>
sqlite3.h:#define SQLITE_LIMIT_VARIABLE_NUMBER           9
sqlite3.h:** parameter [SQLITE_LIMIT_VARIABLE_NUMBER] (default value: 999).
[2715 john@Johns-MacBook-Pro sqlite/3.16.2/include]% grep MAX *
sqlite3.h:** [SQLITE_MAX_MMAP_SIZE] compile-time option.)^
sqlite3.h:** [limits | SQLITE_MAX_<i>NAME</i>].
sqlite3.h:** (The "_LIMIT_" in the name is changed to "_MAX_".))^
sqlite3.h:** statement and try to run it again. As many as [SQLITE_MAX_SCHEMA_RETRY]
sqlite3.h:** [SQLITE_MAX_LENGTH].
sqlite3.h:** char zPathBuf&#91;MAX_PATH + 1&#93;;
sqlite3.h:** meaningful if SQLite is compiled with [YYTRACKMAXSTACKDEPTH].</dd>)^
sqlite3.h:#define SQLITE_DBSTATUS_MAX                 11   /* Largest defined DBSTATUS */
```

**Comment by rnewman** [comment]
Only sqlite3.c:

```
10780:#ifndef SQLITE_MAX_VARIABLE_NUMBER
10781:# define SQLITE_MAX_VARIABLE_NUMBER 999
14829:** Usually it is 16-bits.  But if SQLITE_MAX_VARIABLE_NUMBER is greater
14837:#if SQLITE_MAX_VARIABLE_NUMBER<=32767
140256:  SQLITE_MAX_VARIABLE_NUMBER,      /* IMP: R-38091-32352 */
140334:  assert( aHardLimit[SQLITE_LIMIT_VARIABLE_NUMBER]==SQLITE_MAX_VARIABLE_NUMBER);
```

**Comment by jgallagher** [comment]
Hm, doesn't that mean these constants should be considered implementation details? If they're only in the .c they aren't accessible by _any_ clients.

**Comment by rnewman** [comment]
Perhaps so.

They're accessible to clients compiled at the same time as SQLite — they're compile-time parameters used by sqlite3.c, not defined inside it. To put it another way: there's a build-time define and a C constant both with the same name.

If using a bundled SQLite, it might be useful to bake in that it was compiled with `-DSQLITE_MAX_VARIABLE_NUMBER=500000`. But perhaps I should file an issue against SQLite — after all, it's impossible for a caller to know what is the largest acceptable value to pass to `sqlite3_limit`…

**Comment by rnewman** [comment]
I sent a mail to the sqlite-users list to see if this is intentional or omission!

**Comment by rnewman** [comment]
Conclusion: rather than incrementally broadening the API surface, if a caller wants to find out the max, they can call `sqlite3_limit` twice, once to mutate the value and return the old, and again to mutate it back and return the max. So #221 is fine!

**Comment by jgallagher** [comment]
Added via #221.
