### ISSUE TITLE
Using FromSql<NaiveDateTime>

### ISSUE THREAD

**Issue by simao** [jgallagher/rusqlite#240]
I am trying to use `FromSql<NaiveDateTime>` but I always get a compile error:

```^^^ the trait `rusqlite::types::FromSql` is not implemented for `chrono::NaiveDateTime```

I added the `chrono` feature to my dependencies, but I am probably missing some import,

```
use chrono::prelude::*;
use rusqlite::types::chrono::*; // This fails, chrono is private
```

What imports do I need so I can do `let v: NaiveDateTime = row.get(0)`?

**Comment by jgallagher** [comment]
Try

```rust
use rusqlite::types::FromSql;
```

It's also possible you were running into a chrono version mismatch (see #241). If you're using chrono 0.3, try updating to rusqlite 0.10.

Please reopen if neither of these work!

**Comment by simao** [comment]
Thanks, upgrading to 0.10 worked.

**Comment by BenjaminRi** [comment]
For anyone who encounters this error message, don't forget to add the `chrono` feature in your `rusqlite` dependency, like so:
```
rusqlite = { version = "0.24.1", features = ["bundled", "chrono"] }
```
