### ISSUE TITLE
libsqlite3-sys build fails?

### ISSUE THREAD

**Issue by tnishimura** [jgallagher/rusqlite#242]
Hello, 
I'm on Ubuntu 14.04 64 bit with rust 1.15.1 (via rustup). When I try to cargo build  libsqlite3-sys, I get the error below. I do not understand rust well enough to be able to understand it, help?:

    RUST_BACKTRACE=1 cargo build
    warning: unused manifest key: package.categories
    warning: unused manifest key: package.categories
       Compiling libsqlite3-sys v0.7.0 (file:///home/devuser/tmp/rusqlite/libsqlite3-sys)
    error: failed to run custom build command for `libsqlite3-sys v0.7.0 (file:///home/devuser/tmp/rusqlite/libsqlite3-sys)`
    process didn't exit successfully: `/home/devuser/tmp/rusqlite/libsqlite3-sys/target/debug/build/libsqlite3-sys-2f1b3dd6342c971f/build-script-build` (exit code: 101)
    --- stdout
    cargo:rustc-link-lib=sqlite3
    
    --- stderr
    thread 'main' panicked at 'function not loaded: clang_Type_getNumTemplateArguments', /home/devuser/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.12.0/src/lib.rs:1374
    stack backtrace:
       1:     0x7fdb49d3d89a - std::sys::imp::backtrace::tracing::imp::write::h3188f035833a2635
                            at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
       2:     0x7fdb49d42e4f - std::panicking::default_hook::{{closure}}::h6385b6959a2dd25b
                            at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:349
       3:     0x7fdb49d42a4e - std::panicking::default_hook::he4f3b61755d7fa95
                            at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:365
       4:     0x7fdb49d43297 - std::panicking::rust_panic_with_hook::hf00b8130f73095ec
                            at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:553
       5:     0x7fdb497bd5d3 - std::panicking::begin_panic::haa6e343a5b54e680
                            at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:515
       6:     0x7fdb49827d3f - clang_sys::clang_Type_getNumTemplateArguments::{{closure}}::h0c2d3f28ddee01e4
                            at /home/devuser/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.12.0/src/lib.rs:1374
       7:     0x7fdb4981f06c - clang_sys::with_library::{{closure}}::h1ffb78cc5a033ab2
                            at /home/devuser/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.12.0/src/lib.rs:1374
       8:     0x7fdb497c2e53 - <std::thread::local::LocalKey<T>>::with::h3e8dad0828762723
                            at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/thread/local.rs:245
       9:     0x7fdb4981d653 - clang_sys::with_library::hc0d53806b7807ad6
                            at /home/devuser/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.12.0/src/lib.rs:1374
      10:     0x7fdb49827c7e - clang_sys::clang_Type_getNumTemplateArguments::hf1838a864ebfad58
                            at /home/devuser/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.12.0/src/lib.rs:1374
      11:     0x7fdb4967d8da - bindgen::clang::Type::num_template_args::h640d884314a96d04
                            at /home/devuser/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.21.2/src/clang.rs:695
      12:     0x7fdb4967dab7 - bindgen::clang::Type::template_args::h3a2599d670d854d0
                            at /home/devuser/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.21.2/src/clang.rs:707
      13:     0x7fdb4967e1b3 - bindgen::clang::Type::is_fully_specialized_template::h5c1e49ae97c34501
                            at /home/devuser/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.21.2/src/clang.rs:812
      14:     0x7fdb496aa3e0 - bindgen::ir::ty::Type::from_clang_ty::h86a1559098a29a81
                            at /home/devuser/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.21.2/src/ir/ty.rs:624
      15:     0x7fdb496a44bd - <bindgen::ir::item::Item as bindgen::parse::ClangItemParser>::from_ty_with_id::h7ca76c58ff5281e1
                            at /home/devuser/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.21.2/src/ir/item.rs:1173
      16:     0x7fdb496a3aae - <bindgen::ir::item::Item as bindgen::parse::ClangItemParser>::from_ty::h54f1a53ae78962ea
                            at /home/devuser/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.21.2/src/ir/item.rs:1105
      17:     0x7fdb496a1cf7 - <bindgen::ir::item::Item as bindgen::parse::ClangItemParser>::parse::ha0082f7474cbb45d
                            at /home/devuser/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.21.2/src/ir/item.rs:991
      18:     0x7fdb496b5880 - bindgen::parse_one::h65b6fa5b223019ea
                            at /home/devuser/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.21.2/src/lib.rs:796
      19:     0x7fdb496b5f7c - bindgen::parse::{{closure}}::{{closure}}::h7b0871f9144b839e
                            at /home/devuser/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.21.2/src/lib.rs:829
      20:     0x7fdb4967cb56 - bindgen::clang::visit_children::he119f59ab4c0b93d
                            at /home/devuser/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.21.2/src/clang.rs:539
      21:     0x7fdb4733a99a - <unknown>
      22:     0x7fdb47349b17 - <unknown>
      23:     0x7fdb4733b771 - <unknown>
      24:     0x7fdb4733a6f5 - <unknown>
      25:     0x7fdb47342c34 - clang_visitChildren
      26:     0x7fdb4982c5f5 - clang_sys::clang_visitChildren::h4e7ca184283e4f72
                            at /home/devuser/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.12.0/src/lib.rs:1374
      27:     0x7fdb49679ca4 - bindgen::clang::Cursor::visit::h4f3eefe9b71363ed
                            at /home/devuser/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.21.2/src/clang.rs:358
      28:     0x7fdb496b5fe0 - bindgen::parse::{{closure}}::h57e435037fe22867
                            at /home/devuser/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.21.2/src/lib.rs:829
      29:     0x7fdb49697802 - bindgen::ir::context::BindgenContext::with_module::hfa4a76533473f42d
                            at /home/devuser/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.21.2/src/ir/context.rs:1041
      30:     0x7fdb496b5d8e - bindgen::parse::h76d57805ecbd0af9
                            at /home/devuser/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.21.2/src/lib.rs:828
      31:     0x7fdb496b415f - bindgen::Bindings::generate::h462b9cf228aa65bb
                            at /home/devuser/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.21.2/src/lib.rs:693
      32:     0x7fdb496b2ec5 - bindgen::Builder::generate::hfac9cb0b3c48a31e
                            at /home/devuser/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.21.2/src/lib.rs:438
      33:     0x7fdb49527373 - build_script_build::run_bindgen::h8d472499c0c16a93
                            at /home/devuser/tmp/rusqlite/libsqlite3-sys/build.rs:28
      34:     0x7fdb495280d3 - build_script_build::main::h8db81d2116fef4e1
                            at /home/devuser/tmp/rusqlite/libsqlite3-sys/build.rs:77
      35:     0x7fdb49d4a1aa - __rust_maybe_catch_panic
                            at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
      36:     0x7fdb49d439d6 - std::rt::lang_start::h65647f6e36cffdae
                            at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:434
                            at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panic.rs:351
                            at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/rt.rs:57
      37:     0x7fdb49528512 - main
      38:     0x7fdb486cff44 - __libc_start_main
      39:     0x7fdb49503308 - <unknown>
      40:                0x0 - <unknown>

**Comment by gwenn** [comment]
https://botbot.me/mozilla/rust/2017-01-31/?page=1
> maybe my clang version is too old?
> probably

**Comment by jgallagher** [comment]
Yes, that error is because [rust-bindgen](https://github.com/servo/rust-bindgen) requires a relatively new clang. They recommend 3.9.

**Comment by tnishimura** [comment]
I upgraded my system to 16.04 and it indeed did work. I ran into a few other things but I will create separate issues for those. Thanks!
