### ISSUE TITLE
Build problem on windows

### ISSUE THREAD

**Issue by maxencefrenette** [jgallagher/rusqlite#243]
Hi, building libsqlite3-sys seems to fail on windows.

> Compiling libsqlite3-sys v0.7.0
> error: failed to run custom build command for `libsqlite3-sys v0.7.0`
> process didn't exit successfully: `C:\Users\Maxence\Dropbox\Programmes\Rust\open-table\target\debug\build\libsqlite3-sys-6d5685bf555a012f\build-script-build` (exit code: 101)
> --- stdout
> cargo:rustc-link-lib=sqlite3
> wrapper.h:1:10: fatal error: 'sqlite3.h' file not found, err: true
> 
> --- stderr
> wrapper.h:1:10: fatal error: 'sqlite3.h' file not found
> thread 'main' panicked at 'could not run bindgen on header wrapper.h: ()', C:\bot\slave\stable-dist-rustc-win-msvc-64\build\src\libcore\result.rs:837
> note: Run with `RUST_BACKTRACE=1` for a backtrace.

Maybe something isn't configured properly on my side, but there isn't any documentation on what I need to have installed.

**Comment by gwenn** [comment]
https://github.com/jgallagher/rusqlite/issues/235#issuecomment-279428035

Could you please try to set SQLITE3_LIB_DIR and SQLITE3_INCLUDE_DIR environment variables ?

**Comment by maxencefrenette** [comment]
What do I set them to ? What format of sqlite do I download ? It would help a great deal if this was documented in the readme.

I also discovered that I could just do this to bundle sqlite with my executable by putting this in my Cargo.toml. This makes everything a lot easier.

```toml
[dependencies.rusqlite]
version = "0.10.0"
features = ["bundled"]
```

**Comment by jgallagher** [comment]
Yes, `bundled` is exactly what I was going to suggest. SQLITE3_LIB_DIR and SQLITE3_INCLUDE_DIR are primarily intended for using a prebuilt SQLite library.

I agree that we need better build-time documentation in the README. I'm currently experimenting with some ideas to simplify the build process (cc #244), and will add docs as part of that change.

**Comment by jgallagher** [comment]
This should be less painful as of #247. `bundled` continues to be the simplest way to solve build problems, and the README now has a build section that notes this.
