### ISSUE TITLE
Alternatives to running bindgen at buildtime?

### ISSUE THREAD

**Issue by jgallagher** [jgallagher/rusqlite#244]
Running bindgen at build time solves a hard problem, but I was afraid of things like #242 and #243 happening. Is there a way to solve the same problem (generated binding version mismatch with runtime linked version) without requiring all rusqlite users to install a new-ish Clang?

Ideas:

* Make no changes but add better documentation. At least - add a link to rust-bindgen to the README with short descriptions of common problems.
* Embed bindings for the oldest version of SQLite we support and use those. Currently this is 3.6.8 with no features or 3.7.4 with all features; we'd probably just bump the min version to 3.7.4 and embed that.
* Embed bindings created against all the point releases of SQLite used by features and pick which one to use at build time. This would be 5 sets currently (3.6.8, 3.6.11, 3.6.23, 3.7.3, 3.7.4).
* Embed bindings for every version of SQLite since 3.6.8, inspect the library we find at buildtime, and use the matching one.

@gwenn thoughts?

**Comment by gwenn** [comment]
I am biased:
Now that `rusqlite` is a [C](https://github.com/jgallagher?tab=repositories&q=rusqlite&language=c) project, we have to manage the related build issues :smile:

The simple AppVeyor/Travis build scripts work and describe the minimal setup.
Perhaps we can add comments to say why `llvm-3.9` is installed or why `SQLITE3_LIB_DIR` is set ?

Perhaps we should add a FAQ relating build errors to possible solutions ?
Perhaps we should ask rustaceans for suggestions ?

**Comment by jgallagher** [comment]
Definitely agreed on the last one! https://www.reddit.com/r/rust/comments/5x5em7/pain_points_using_rustbindgen_at_buildtime/
