### ISSUE TITLE
FromSQL for u64, usize, isize

### ISSUE THREAD

**Issue by SeanTater** [jgallagher/rusqlite#250]
Is there a reason FromSQL is not defined for u64, usize, and isize (particularly the latter two)?
I do a lot of explicit casts for those types and it seems like it would be supported by SQLite.

**Comment by jgallagher** [comment]
There is, unfortunately. SQLite's APIs for getting integral values out give us the option of a C `int` (size varies by platform, but usually 32 bits) or a signed 64-bit integer. Adding `FromSql` impls for `u64` and `usize` would require us to decide how to handle negative numbers coming back from SQLite - either return an out of range error (like we do if you try to get a the value `1000` into an `u8`, for example) or reinterpret it as a very large `u64`. _Probably_ the latter is what makes the most sense for most projects, but I don't like doing implicit/unseen conversions like that in library code.

We could definitely add an impl for `isize` though. Would that be helpful even without the other two?

**Comment by SeanTater** [comment]
Isize is probably the least exciting of the three but I see now why u64 is not there. Still, isize would be nice and maybe its worth a note in the docs.

- Also, thanks for maintaining this library, it's a great help to the community IMO.

**Comment by ruffsl** [comment]
> or reinterpret it as a very large u64. Probably the latter is what makes the most sense for most projects

I feel like if the user specifies u64 to FromSQL, then casting the 64 bits representation to uint type would be a reasonable interpretation if the user knew the sql int stored was u64 to start with. Has anything improved, or any rusty conventions surfaced since this issue was ticketed in 2017?

> Callers can work around this by fetching values as i64 and then doing the interpretation themselves or by defining a newtype and implementing

As I'm new to rust, could I see an example of what is meant by that in docs?
I'm not sure how conversions are defined in rust vs something like c standard:

>In general, conversions in C are defined to operate on values, not on representations.
https://stackoverflow.com/questions/50605/signed-to-unsigned-conversion-in-c-is-it-always-safe

**Comment by gwenn** [comment]
I guess we can use [to_be_bytes](https://doc.rust-lang.org/std/index.html?search=to_be_bytes).
Like suggested by #557 for i128.

**Comment by erayerdin** [comment]
I wouldn't like to revive an old issue, but what about `&str`? Compiler complains:

```
the trait `rusqlite::types::from_sql::FromSql` is not implemented for `&str`
```

when I use `row.get` method inside a `statement.query_map` closure.

Version: "0.21.0"

**Comment by thomcc** [comment]
It would be nice to support `str`, but the result of `FromSql` must be owned. I've tried a couple times, I think you can make it work as borrowed but it makes every function signature substantially more complicated as it takes parameterizing the trait itself by a lifetime -- meaning every bound needs to be a higher ranked trait bound. So I don't think it would be an ergonomics win, or close.

Maybe there's a way around this, idk, just use `String` instead though in the meantime.
