### ISSUE TITLE
Duplicated constants

### ISSUE THREAD

**Issue by gwenn** [jgallagher/rusqlite#252]
Between `bindgen.rs` and `error.rs`:
```sh
$ rg -l 'pub const SQLITE_OK'
...
libsqlite3-sys/sqlite3/bindgen_bundled_version.rs
libsqlite3-sys/src/error.rs
$ rg -l 'pub const SQLITE_IOERR_READ'
...
libsqlite3-sys/sqlite3/bindgen_bundled_version.rs
libsqlite3-sys/src/error.rs
```

And also between `bindgen.rs` and `lib.rs`:
```sh
$ rg -l 'SQLITE_LIMIT_LENGTH'
...
libsqlite3-sys/src/lib.rs
libsqlite3-sys/sqlite3/bindgen_bundled_version.rs
```

**Comment by sagebind** [comment]
Also seeing this error on OS X using latest version of rusqlite from crates.io.

**Comment by sagebind** [comment]
@gwenn Not sure why (I'm not sure I understand how the duplicate constants work normally ever), but updating Cargo to a newer version worked for me. I am now using `cargo-0.17.0-nightly` and compiled successfully.

**Comment by jgallagher** [comment]
I can't explain why you got errors and then they went away with a newer cargo, but 0.10.2 (going up on crates.io shortly) should fix this.

**Comment by gwenn** [comment]
There was no error on my side !
And it seems to me that constants are still duplicated:
https://github.com/jgallagher/rusqlite/blob/master/libsqlite3-sys/src/lib.rs#L18-L21
```rust
#[repr(C)]
pub enum Limit {
    /// The maximum size of any string or BLOB or table row, in bytes.
    SQLITE_LIMIT_LENGTH = 0,
``` 
Maybe
```rust
#[repr(C)]
pub enum Limit {
pub enum Limit {
    /// The maximum size of any string or BLOB or table row, in bytes.
    SQLITE_LIMIT_LENGTH = SQLITE_LIMIT_LENGTH as isize,
```
?

And it seems possible to remove https://github.com/jgallagher/rusqlite/blob/master/libsqlite3-sys/src/error.rs#L117-L143, https://github.com/jgallagher/rusqlite/blob/master/libsqlite3-sys/src/error.rs#L146-L147 and https://github.com/jgallagher/rusqlite/blob/master/libsqlite3-sys/src/error.rs#L151-L167 already defined in all supported SQLite versions.
