### ISSUE TITLE
Can I insert multiple rows in a single call?

### ISSUE THREAD

**Issue by tomcumming** [jgallagher/rusqlite#262]
Bonus question: or can I access the built in sanitising functions so I cant construct my own big statement?

**Comment by gwenn** [comment]
In the same table ?
If yes, you can:
http://sqlite.org/releaselog/3_7_11.html
> Enhance the INSERT syntax to allow multiple rows to be inserted via the VALUES clause.
http://sqlite.org/lang_insert.html
```sql
INSERT INTO tbl (...) VALUES (?, ...), (?, ...);
```

**Comment by tomcumming** [comment]
@gwenn sorry I mean I have a vector of records I need to insert, where I don't know the count at compile time. At the moment I build up a big insert statement as a string and then execute without any parameters. Ideally, I would prepare some statement and then execute it with my vector of (vector of) params

**Comment by jgallagher** [comment]
Can I ask why you want to do it in one insert instead of preparing the statement, then looping over the vector and executing it for each entry?

**Comment by tomcumming** [comment]
@jgallagher it seems to be performing very slowly when I execute a prepared insert statement in a loop (the prepare is before the loop body). I have not tried doing this inside a transaction which I just realized might be the cause, maybe it's committing after every execute ? I will test this tonight

**Comment by jgallagher** [comment]
Yeah, that was going to be my next suggestion. Bulk inserts are _very_ slow unless you wrap them in a single transaction - http://stackoverflow.com/questions/3852068/sqlite-insert-very-slow

**Comment by tomcumming** [comment]
Yeah its lightning quick when in a tx, thanks!

**Comment by SET001** [comment]
> In the same table ? If yes, you can: http://sqlite.org/releaselog/3_7_11.html
> 
> > Enhance the INSERT syntax to allow multiple rows to be inserted via the VALUES clause.
> 
> http://sqlite.org/lang_insert.html
> 
> ```sql
> INSERT INTO tbl (...) VALUES (?, ...), (?, ...);
> ```

how to pass params to `.execute` in this case?
