### ISSUE TITLE
Feature request: A method to easily access and set the user_version pragma

### ISSUE THREAD

**Issue by porglezomp** [jgallagher/rusqlite#265]
I'm working on doing the schema versioning for my database, and I need to use `user_version`. It seems like it would be nice to have an extremely easy to get at it.

**Comment by gwenn** [comment]
Do you mean:
```rust
let user_version: i64 = db.query_row("PRAGMA user_version", &[], |row| row.get(0)).unwrap();
db.execute(&format!("PRAGMA user_version = {}", 1), &[]).unwrap();
```
are too verbose ?

**Comment by porglezomp** [comment]
That's what I'm using right now. I hadn't used it long enough at that point to get the philosophy of this library, I can see now that having lots of specialized methods isn't really the style here.

**Comment by gwenn** [comment]
rusqlite 0.17 released
