### ISSUE TITLE
build bundled sqlite with HAVE_USLEEP

### ISSUE THREAD

**Issue by Dushistov** [jgallagher/rusqlite#268]
From http://mailinglists.sqlite.org/cgi-bin/mailman/private/sqlite-dev/2017-May/002978.html 

> I have been testing the Android bindings (both a local modified version and 
> the vanilla AAR version) and found that my app periodically pauses for about a 
> second when using these libraries. It does not do this with SqlCipher.
>
> The app itself suffers the pauses when rapidly scrolling a list; the scrolling 
> causes many transactions in rapid succession.
>
> I have traced the problem to the native call to execute the "begin 
> transaction" statement.
>
> The delay is almost exactly 1000ms which leads me to believe it's engaged in 
> some kind of backoff to wait for another transaction.

>OK; found the problem. The default AAR build is missine HAVE_USLEEP; the result 
>is *all* calls to sleep take a minimum of 1 second.

rusqlite for at least `--target=x86_64-unknown-linux-gnu` and `arm-linux-androideabi` builds without `HAVE_USLEEP` defined, can you enable this option at least for all targets with linux or android in their names?

**Comment by jgallagher** [comment]
This should be fixed as of #263 and 0.12.0 (to be released shortly). Please reopen if you're still seeing this after upgrading!
