### ISSUE TITLE
Implement ToSql for str and [u8]

### ISSUE THREAD

**Issue by albel727** [jgallagher/rusqlite#269]
As of now, `ToSql` is implemented for all integral types directly via macro, i.e. expanded definition is like
`impl ToSql for i32`.

But for `str` and `[u8]` it's implemented only via blanket reference implementation 
`impl<'a, T: ?Sized> ToSql for &'a T where &'a T: Into<ToSqlOutput<'a>>` 

so it's like
`impl ToSql for &str`.
`impl ToSql for &[u8]`.

But considering that `fn to_sql(&self) -> Result<ToSqlOutput>;` also takes `self` by reference, nothing prevents implementing `ToSql` directly on `str` and `[u8]`, e.g.

```
impl ToSql for str {
    fn to_sql(&self) -> Result<ToSqlOutput> {
        Ok(ToSqlOutput::from(self))
    }
}

impl ToSql for [u8] {
    fn to_sql(&self) -> Result<ToSqlOutput> {
        Ok(ToSqlOutput::from(self))
    }
}
```

Now, why would this be useful. Well, the current implementation lacks symmetry with respect to some traits, e.g. `Borrow`. Suppose someone wanted more type safety, than is available from sqlite, by restricting allowed input types, while accepting not only specified owned types, but also their borrowed counterparts, like you can see in e.g. [`HashMap::get()`](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.get). Consider the following definition.

https://gist.github.com/albel727/ae08b889db37232aa80903a8edb7e4db

As it stands, it works well for all integral types, since, e.g. `i32` is `Borrow<i32>`, but when things come to `String` and `Vec<u8>`, it fails to do the obvious thing, e.g. `SqliteMap::get()` works only with the owned types and doesn't compile with `str` and `[u8]` arguments, even though nothing technically prevents them from being used. This is due to the lack of the aforementioned direct implementations of `ToSql` on `str` and `[u8]`, since `String` is `Borrow<str>`, not `Borrow<&str>`, and `Vec<u8>` is `Borrow<[u8]>`, not `Borrow<&[u8]>`.

I'd also have thought that e.g. `impl ToSql for str` would obviate the need for `impl ToSql for String` due to Deref coercions, but unfortunately this is not so, so both definitions are necessary.

Anyway, adding the suggested impls resolves the problem as expected and doesn't seem to break anything, at least `diesel` crate has compiled without problems for me using modified `rusqlite`.

**Comment by albel727** [comment]
PS. Suggested impls seem to kind of render blanket implementation
`impl<'a, T: ?Sized> ToSql for &'a T where &'a T: Into<ToSqlOutput<'a>>`
useless, but removing this impl is backward incompatible with crates that had to use arrays with `&&str` elements everywhere previously.

**Comment by jgallagher** [comment]
I agree, I don't see a reason not to add those impls. #280 does so; thanks!
