### ISSUE TITLE
Best way to use pragmas?

### ISSUE THREAD

**Issue by dgrnbrg** [jgallagher/rusqlite#273]
Hi, I'm trying to use pragmas in my SQLite interactions. I am invoking

```rust
try!(conn.execute("PRAGMA synchronous = OFF;", &[]));
try!(conn.execute("PRAGMA journal_mode = OFF;", &[]));
```

However, these lines fail with the error: `Error: Execute returned results - did you mean to call query?`. Should I be calling `query`? If so, I can't figure out from sqlite's docs what the return value is that I should be expecting.

Thank you for your help in using this library correctly!

**Comment by gwenn** [comment]
Just try with the SQLite shell:
```sh
$ sqlite3
sqlite> PRAGMA synchronous = OFF;
sqlite> -- nothing is returned, so it should be okay to use `conn.execute`
sqlite> PRAGMA journal_mode = OFF;
off
sqlite> -- activated mode is returned, so `conn.execute_batch` should be used instead if you don't care of the result.
```

Or read the doc thoroughly :smile:
http://sqlite.org/pragma.html#pragma_journal_mode
> The new journal mode is returned.

Regards.

**Comment by dgrnbrg** [comment]
You are so right, thank you! For future readers of this issue, here is my implementation which casts any errors into the appropriate application-level error type without panicking:

```rust
try!(conn.execute("PRAGMA synchronous = OFF;", &[]));
try!(conn.query_row_and_then("PRAGMA journal_mode = OFF;", &[], |row| -> Result<()> {
    row.get_checked::<_,String>(0)? == "off".to_owned();
    Ok(())
}));
```

**Comment by xpe** [comment]
Good question and self-answer here -- thanks.

For others that find their way here, I recommend considering `PRAGMA journal_mode = WAL;`. Read more about it at:
* https://sqlite.org/wal.html
* https://sqlite.org/pragma.html#pragma_journal_mode

**Comment by gwenn** [comment]
A more appropriate answer is https://docs.rs/rusqlite/0.25.3/rusqlite/?search=pragma
