### ISSUE TITLE
Can't compile crate for Ubuntu 16.04

### ISSUE THREAD

**Issue by elliotstronge** [jgallagher/rusqlite#275]
On first compilation after including the crate I get the errors:

> error[E0432]: unresolved import `super::RawStatement`
 --> /home/elliot/.cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite-0.11.0/src/statement.rs:7:25
  |
7 | use super::{Connection, RawStatement, Result, Error, ValueRef, Row, Rows, AndThenRows, MappedRows};
  |                         ^^^^^^^^^^^^ no `RawStatement` in the root. Did you mean to use `raw_statement`?

> error[E0432]: unresolved import `super::ValueRef`
 --> /home/elliot/.cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite-0.11.0/src/statement.rs:7:54
  |
7 | use super::{Connection, RawStatement, Result, Error, ValueRef, Row, Rows, AndThenRows, MappedRows};
  |                                                      ^^^^^^^^ no `ValueRef` in the root

> error[E0277]: the trait bound `raw_statement::RawStatement: std::convert::From<statement::Statement<'_>>` is not satisfied
  --> /home/elliot/.cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite-0.11.0/src/cache.rs:85:40
   |
85 |             self.cache.cache_stmt(stmt.into());
   |                                        ^^^^ the trait `std::convert::From<statement::Statement<'_>>` is not implemented for `raw_statement::RawStatement`
   |
   = note: required because of the requirements on the impl of `std::convert::Into<raw_statement::RawStatement>` for `statement::Statement<'_>`

> error: the type of this value must be known in this context
  --> /home/elliot/.cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite-0.11.0/src/statement.rs:25:36
   |
25 |             let s = str::from_utf8(slice.to_bytes()).unwrap();
   |                                    ^^^^^^^^^^^^^^^^

Any ideas on how to fix this? I'm not sure what's causing it, I haven't encountered this before. Apologies in advance if it's something silly I've done.

**Comment by gwenn** [comment]
Maybe the rust version ?
```sh
$ rustc -V
```

**Comment by elliotstronge** [comment]
Must have been the rust version. A fresh reinstall solved it. Thanks for your help.
