### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by gsingh93** [jgallagher/rusqlite#29]
I believe the documentation is out of date. For example, `SqliteConnection::open` takes a `Path`, not a `&str`.

**Comment by jgallagher** [comment]
Hmm you're right. It's supposed to be built by Travis when it runs the tests. I'll kick it around and see if I can get it to refresh. Thanks.

**Comment by gsingh93** [comment]
Unrelated to the documentation issue, but it would be nice if these methods took a `T: AsPath` instead of a `Path`.

**Comment by gsingh93** [comment]
Er, that got changed to `AsRef<Path>`, not `AsPath`.

**Comment by jgallagher** [comment]
Good idea - opened #33 to track that.
