### ISSUE TITLE
Export SQLite error codes and extended error codes

### ISSUE THREAD

**Issue by koutheir** [jgallagher/rusqlite#293]
In order to be able to deal with SQLite errors (apart from printing them), we need to be able to compare the contents of `rusqlite::ffi::Error` contained inside `rusqlite::Error::SqliteFailure` with the error constants inside `libsqlite3-sys/src/error.rs`.

Please export them in some way, or provide another way to achieve this.

**Comment by gwenn** [comment]
There is a [comment](https://github.com/jgallagher/rusqlite/blob/master/libsqlite3-sys/src/error.rs#L113) that explains why they are not exported/public:
> These are not public because our bindgen bindings export whichever constants are present

And, you can check that they are already visible.
For example, https://docs.rs/libsqlite3-sys/0.8.1/libsqlite3_sys/constant.SQLITE_IOERR_LOCK.html
If some are missing, you should use one feature (maybe "libsqlite3-sys/min_sqlite_version_3_7_16") to use a more recent SQLite3 version with the missing constants.

**Comment by koutheir** [comment]
This is how I solved the issue.

In `Cargo.toml`, I added the following line to the `[dependencies]` section:
```
libsqlite3-sys  = { version = "0.8", features = ["min_sqlite_version_3_7_16"] }
```

In `main.rs`, I added:
```
extern crate libsqlite3_sys;
```

In the file where I need to use the constants, I added:
```
use libsqlite3_sys::{SQLITE_CONSTRAINT_PRIMARYKEY, SQLITE_CONSTRAINT_UNIQUE};
```

So that I could write code like:
```
match err {
  rusqlite::Error::SqliteFailure(err, desc) => {
    if err.code == rusqlite::ErrorCode::ConstraintViolation &&
      (err.extended_code == SQLITE_CONSTRAINT_PRIMARYKEY ||
      err.extended_code == SQLITE_CONSTRAINT_UNIQUE) {
        // Specific error handling
```

**Comment by gwenn** [comment]
I don't know exactly why 3.6.8 is still used (released on 2009-01-12, 8 years old) as the default!
