### ISSUE TITLE
Is the crate abandoned?

### ISSUE THREAD

**Issue by vityafx** [jgallagher/rusqlite#297]
The latest commit was made at 29 of May 2017. No respones on the PRs and issues. The crate can not be used with modern dependencies. What is going on?

**Comment by gwenn** [comment]
https://github.com/jgallagher/rusqlite/pull/264#issuecomment-304670030

**Comment by jgallagher** [comment]
Not abandoned, just was out of commission for a while as @gwenn noted. I'm working through the PRs and will push out a new version soon (today or tomorrow).

However, I have much less involvement with Rust than I have in the past, so I would consider this crate to be in "maintenance mode". I'll continue to push updates for things like dependency changes and bug fixes, but am unlikely to merge any major feature enhancements. If that becomes problematic, I'm open to handing off continued development to someone else.
