### ISSUE TITLE
Execute statement with variable number of parameters?

### ISSUE THREAD

**Issue by arthurmilliken** [jgallagher/rusqlite#312]
I'm a rust newbie, so please forgive my ignorance if this is a stupid question...

How do I execute statements with a variable number of parameters? Let's say that the statement is:

`"INSERT INTO TableName(ColumnA, ColumnB, ColumnC) VALUES (?1, ?2, ?3)"`

But `TableName`, Columns, and number of columns are not known at compile time. Is there a way of coercing an iterator over a collection of strings into a `&[&ToSql]` type?

**Comment by SolraBizna** [comment]
Greetings, fellow Rust newbie. The following should work:

```rust
let params: Vec<&ToSql> = my_iterator.collect();
my_statement.execute(params.as_slice());
```

Hope it's still useful months later.

**Comment by arthurmilliken** [comment]
Hi @SolraBizna , this does not seem to work:
`
error[E0308]: mismatched types
  --> src/load/mod.rs:61:34
   |
61 |     conn.execute(&schema.insert, fields.as_slice())?; // THIS LINE FAILS
   |                                  ^^^^^^^^^^^^^^^^^ expected trait load::rusqlite::types::ToSql, found str
   |
   = note: expected type '&[&load::rusqlite::types::ToSql]'
              found type '&[&str]'
`

Here is my source:
`
  for record in rdr.records() {
    let row = record?;
    println!("{}", schema.insert);
    let fields: Vec<&str> = row.iter().collect();
    println!("            {:?}", fields);
    conn.execute(&schema.insert, fields.as_slice())?; // THIS LINE FAILS
  }
`

**Comment by gwenn** [comment]
Not related to rusqlite but to Rust :
```
use std::fmt::Debug;
fn test(values: &[&Debug]) {
    println!("{:?}", values);
}
fn main() {
    let fields = vec!["field1", "field2"];
    test(fields.as_slice()); // THIS LINE FAILS
}
```
And I don't know the correct/idiomatic way to cast a `&[&str]` into a `&[&Debug]`.

**Comment by arthurmilliken** [comment]
I suspect it is impossible, since the Rust compiler cannot determine the correct memory allocation at compile time.

**Comment by gwenn** [comment]
This works:
```rust
use std::fmt::Debug;
fn test<T: Debug + ?Sized>(values: &[&T]) {
    println!("{:?}", values);
}
fn main() {
    let fields = vec!["field1", "field2"];
    test(fields.as_slice()); // THIS LINE FAILS
}
```
But I am not sure that we should apply this change wherever `&[&ToSql]` is used !

**Comment by zetok** [comment]
Hi, I'm just dropping by to say that I've also run into this problem, and as a work-around I'm just directly putting escaped values in SQL statements.

https://gitlab.com/zetok/ods2sql/blob/3871473fa88cfc274c15724e91cdf2ace9fa55f6/src/main.rs#L255

It only "works" because I'm dealing with text data, but it would be a deal breaker if one was to try to work with binary data.

**Comment by gwenn** [comment]
https://github.com/sfackler/rust-postgres/issues/265
https://github.com/rust-lang/rust/issues/42499
> The problem in your case is that there's no way to convert &[&T] to &[&Trait] without an allocation. Maybe your api should be generic or take an iterator?

**Comment by gwenn** [comment]
rusqlite 0.15 released

**Comment by rokit** [comment]
What about for named parameters?
