### ISSUE TITLE
Add support of iOS

### ISSUE THREAD

**Issue by volodg** [jgallagher/rusqlite#314]
I've tried to compile this lib for iOS platform and got an error:

cargo lipo --release
   Compiling libsqlite3-sys v0.9.0
error: failed to run custom build command for `libsqlite3-sys v0.9.0`
process didn't exit successfully: `./target/release/build/libsqlite3-sys-84de1213d430f3c9/build-script-build` (signal: 6, SIGABRT: process abort signal)
--- stderr
dyld: mach-o, but built for simulator (not macOS)

Cargo exited unsuccessfully: exit code: 101

**Comment by volodg** [comment]
It was a local cache issue

**Comment by hajsf** [comment]
Hi @volodg 

Did you get it running at iOS, I just opened this issue: https://github.com/jgallagher/rusqlite/issues/437

Appreciate if you can help. thanks

**Comment by volodg** [comment]
Yep, everything was fine on iOS

**Comment by hajsf** [comment]
Hi @volodg 

I was able to compiled for iOS, but got error while exciting.

I tried simple statement:
```rust
    let conn = Connection::open_in_memory().unwrap();
    conn.execute(
        "CREATE TABLE person (
                  name            TEXT NOT NULL,
                  )",
        NO_PARAMS,
    ).unwrap();

    conn.execute(
        "INSERT INTO person (name, time_created, data)
                  VALUES (?1)",
        &[&to.to_owned() as &ToSql],
    ).unwrap();
```

The error I got is:

> symbol(s) not found for architecture x86_64
