### ISSUE TITLE
Update to latest version of SQLite3 3.22.0

### ISSUE THREAD

**Issue by pbtrung** [jgallagher/rusqlite#326]
Is it possible to update to the latest version of SQLite3 (3.22.0)?
No breaking change to the APIs. Just some needed bug fixes.
Thanks.

**Comment by galich** [comment]
SQLite 3.24.0 introduced UPSERT, would be great to have it

https://www.sqlite.org/lang_UPSERT.html

**Comment by gwenn** [comment]
Would you mind testing the shell script (https://github.com/jgallagher/rusqlite/blob/master/libsqlite3-sys/upgrade.sh) and send a PR ?

**Comment by gwenn** [comment]
libsqlite3-sys 0.9.3 released
