### ISSUE TITLE
Use case: Data Change Notification Callbacks

### ISSUE THREAD

**Issue by amilajack** [jgallagher/rusqlite#328]
I want to use [Data Change Notification Callbacks](https://sqlite.org/c3ref/update_hook.html) but I can only do that by using a raw pointer to sqlite. [This comment](https://github.com/jgallagher/rusqlite/blob/master/src/lib.rs#L552-L559) here says that raw pointers should not be used and that an issue should be made describing the use case so I decided I'd do that. Thoughts on adding support for this?

**Comment by gwenn** [comment]
Maybe #266 ?

**Comment by gwenn** [comment]
rusqlite 0.14 released
