### ISSUE TITLE
Is it possible to wait until the database is unlocked?

### ISSUE THREAD

**Issue by vityafx** [jgallagher/rusqlite#331]
I tried to use `r2d2` + `diesel` + `sqlite` crates for working with my sqlite database from multiple threads. However, it seems to be useless to use connection pool since everytime the database is locked the error is returned immediately without even waiting until it is unlocked by another thread. Is there a wait to specify some timeout for a connection and make it wait until one is free?

**Comment by gwenn** [comment]
In the same process, yes you can.
See [sqlite3_unlock_notify](http://sqlite.org/c3ref/unlock_notify.html).
But you will need to [patch](https://github.com/jgallagher/rusqlite/pull/317) `rusqlite`.

**Comment by vityafx** [comment]
Thanks, cool. Why nobody merges it? And why I think it should be enabled always if it is used from r2d2.

**Comment by gwenn** [comment]
See https://github.com/jgallagher/rusqlite/issues/297#issuecomment-343772632

**Comment by vityafx** [comment]
Thanks

**Comment by ajensen123** [comment]
Having looked at this branch's code a little more closely, it appears that simply enabling the "unlock_notify" feature means that the internal "prepare" statement will wait until the database is unlocked before exiting. Is there any chance that it could end up waiting forever or an excessively long time?

I compiled the application with the following cargo.toml dependency defined. Is this all I have to do to enable this feature? (I'm a Rust Newbie).

`rusqlite = {  git = "https://github.com/gwenn/rusqlite", branch = "unlock-notify", features = ["bundled","chrono","unlock_notify"]}`

**Comment by gwenn** [comment]
Currently, there is no timeout but you just have to replace the [wait](https://github.com/jgallagher/rusqlite/pull/317/files#diff-b4aea3e418ccdb71239b96952d9cddb6R915) by a [wait_timeout](https://doc.rust-lang.org/std/sync/struct.Condvar.html#method.wait_timeout)

**Comment by tcr** [comment]
@gwenn Can this be closed as of https://github.com/jgallagher/rusqlite/pull/349 ?

**Comment by gwenn** [comment]
Indeed, in [next](https://github.com/jgallagher/rusqlite/pull/339/files#diff-9b8fab691c00b9e5380b19ce882f3271R14) release.

**Comment by gwenn** [comment]
rusqlite 0.14 released
