### ISSUE TITLE
Improving the documentation concerning Connection::open

### ISSUE THREAD

**Issue by kkayal** [jgallagher/rusqlite#332]
The documentation says:

`Connection::open(path) is equivalent to Connection::open_with_flags(path, SQLITE_OPEN_READ_WRITE | SQLITE_OPEN_CREATE)`

The source is located in lib.rs line 197.

This doesn't compile as is. So, I have opened a [stackoverflow question](https://stackoverflow.com/questions/48829416/how-to-open-a-connection-with-flags-using-the-rusqlite-crate) and received a good answer.

So I suggest to replace this statement with the following:

`Connection::open(path) is equivalent to Connection::open_with_flags(path, OpenFlags::SQLITE_OPEN_READ_WRITE | OpenFlags::SQLITE_OPEN_CREATE)`

**Comment by gwenn** [comment]
Indeed.
The regression was introduced by 28d58529b799dbeeeacd4096229ba935a833ef45
See https://github.com/rust-lang-nursery/bitflags/releases/tag/1.0.0

**Comment by gwenn** [comment]
rusqlite 0.14 released
