### ISSUE TITLE
Make @gwenn a contributor

### ISSUE THREAD

**Issue by rnewman** [jgallagher/rusqlite#336]
@gwenn has been pushing up a bunch of PRs, and there are other issues and PRs languishing, including one that updates to a more recent version of SQLite to fix downstream build issues.

@jgallagher, if you have limited bandwidth to maintain rusqlite right now, might I suggest adding some other folks who can push fixes and cut releases?

**Comment by jgallagher** [comment]
Yes, I apologize for being MIA. I just added @gwenn as a collaborator.

@gwenn, are you interested in taking ownership of rusqlite? I'd be happy to handing it off if you'd like - my ability to maintain is not likely to improve greatly in the foreseeable future. I'm not sure how to transfer ownership on crates.io but am sure it's possible.

**Comment by gwenn** [comment]
I would prefer someone more experimented in rust (I am just playing with rusqlite). But I can certainly help.

**Comment by rnewman** [comment]
I’m happy to offer Rust guidance for the foreseeable future.
