### ISSUE TITLE
Dynamic SELECT Query

### ISSUE THREAD

**Issue by saeedinfact** [jgallagher/rusqlite#337]
Let's say i want to do a "SELECT" query on one of my tables, according to the example i should do something like this:
```
    let person_iter = stmt.query_map(&[], |row| {  
        Person {  
            id: row.get(0),  
            name: row.get(1),  
            time_created: row.get(2),  
            data: row.get(3)  
        }  
    }).unwrap();  

    for person in person_iter {  
        println!("Found person {:?}", person.unwrap());  
    }  
```
The problem here is, this code is not so dynamic when it comes to selecting tables with different column sizes & column types, because in order to find a row you have to create an iterator and in order to create an iterator you have to statically specify the "row.get(num)" and assign them to correct variables.
Is there a way to dynamically execute a "SELECT" command from an external input?
I am simply looking for a function that takes an SQLite "SELECT" query and returns the iterator (like "person_iter") as the result.

**Comment by gwenn** [comment]
You can do dynamic SELECT (see https://github.com/jgallagher/rusqlite/pull/109/files).

**Comment by saeedinfact** [comment]
Thank you for response gwenn, i believe this solves my problem.
