### ISSUE TITLE
How to pass in a vector as a single parameter that used in "IN/ NOT IN" clause?

### ISSUE THREAD

**Issue by Xudong-Huang** [jgallagher/rusqlite#345]
Hi
Is it possible that I can pass in a vector as a single parameter that used in a "WHERE .... IN" clause?
e.g.
```rust
let students = vec!["John", "Tom", "Ann"];
let mut stmt = tx.prepare_cached("UPDATE person SET is_student=1 WHERE name IN (?)")?;
stmt.execute(&[&students])?;
```

Seems that I have to construct some sql string like this now,
```
UPDATE person SET is_student=1 WHERE name IN ('John', 'Tom', 'Ann')
```
but this way I can't get the benefits of cached statements, because the students set is a dynamic value during running.

**Comment by gwenn** [comment]
There is one  but you need to [patch](https://github.com/jgallagher/rusqlite/pull/130/files#diff-643e668c1a640530a9f41ff4e16be828) and only integer are supported.
A better solution would be to port the [carray](https://www.sqlite.org/cgi/src/artifact/ed96c218ea940b85) extension to Rust.

**Comment by Xudong-Huang** [comment]
Thanks for the update. Is there a plan that could support other types within an iterator as a single parameter? I think it would be very useful to support pass in `Rows` or `Iterator` as a single parameter

**Comment by gwenn** [comment]
If you have `Rows`, use the associated `SELECT` as a sub-select directly:
```sql
UPDATE person SET is_student=1 WHERE name IN (SELECT ...);
``` 
Or you can still use a temporary table:
```sql
CREATE TEMPORARY TABLE student (name TEXT);
```
```sql
--- loop on your iterator
INSERT INTO student (name) VALUES (?)
```
```sql
UPDATE person SET is_student=1 WHERE name IN (SELECT name FROM temp.student);
```
```sql
DROP TABLE temp.student;
```

**Comment by gwenn** [comment]
[carray module](https://github.com/jgallagher/rusqlite/pull/130/commits/1a1d41b4e454374356e74f97432022b1e1444208) has been ported.

So you should be able to do this:
```sql
UPDATE person SET is_student=1 WHERE name IN rarray(?);
```

**Comment by Xudong-Huang** [comment]
wow, nice! Thanks 😄

**Comment by gwenn** [comment]
If you don't mind, I am going to reopen this issue because the fix is an PR still to be merged.

**Comment by davemilter** [comment]
I also need this functionality. I have Vec<i64> of ids,
and I want to read it from db with one select:

```SQL
SELECT {all_sql_fields} FROM {tbl} WHERE key IN (?1)
```

Is #130 allow this directly, or I should create "virtual tables"?

**Comment by gwenn** [comment]
@davemilter #130 + [array](https://github.com/jgallagher/rusqlite/pull/130/files#diff-80398c5faae3c069e4e6aa2ed11b28c0R35) feature + `bundled` or `buildtime_bindgen` feature.

**Comment by gwenn** [comment]
rusqlite 0.14 released

**Comment by rokit** [comment]
So `rarray` is used in the query, but what does the code look like to pass in a `Vec<String>` for `"John", "Tom", "Ann"` as specified in the original question? `Vec<String>` doesn't implement `ToSql`.

**Comment by gwenn** [comment]
> So `rarray` is used in the query, but what does the code look like to pass in a `Vec<String>` for `"John", "Tom", "Ann"` as specified in the original question? `Vec<String>` doesn't implement `ToSql`.

https://docs.rs/rusqlite/latest/rusqlite/?search=rarray

**Comment by yaleman** [comment]
@gwenn I've read that link, and searched a lot, and I can't find a tested example anywhere in the rusqlite codebase that refers to a `WHERE` statement that uses an array as a query param.

Given the following code:

```rust
// prepare the statement
let stmt = conn.prepare("SELECT id from table_name WHERE id IN :things");
// get our list of things
let things: Vec<i64> = vec![1,2,3,4];
// turn them into an `Array` type
let id_list: Array = std::rc::Rc::new(
	things
		.into_iter()
		.map(rusqlite::types::Value::from)
		.collect::<Vec<rusqlite::types::Value>>(),
	);
// do the query
let rows = stmt.query_map(named_params! {":idli": &id_list});
```
I end up with an error that shows that it's not putting the params in:

```
near ":things": syntax error" sql: "SELECT id FROM tale_name WHERE id IN :things"
```

Where am I going wrong? I've tried a few different variations including using `WHERE id IN ?` etc etc, to no avail. I'm happy to raise this as a new issue if that's required.

**Comment by asg017** [comment]
Just to give another alternative solution to this kind of problem: You can pass in a JSON array of IDs as a single text string, then unfurl it with `json_each()` in a subquery:

```sql
SELECT id 
FROM table_name 
WHERE id in (SELECT value FROM json_each(?))
```

Where the value you bind is something like `"[1,2,3]"` as text, which you can do with serde_json in Rust.

**Comment by gwenn** [comment]
> // prepare the statement
> let stmt = conn.prepare("SELECT id from table_name WHERE id IN :things");

There is no usage of `rarray` here !
versus
https://docs.rs/rusqlite/latest/rusqlite/vtab/array/index.html#example
```rust
let mut stmt = db.prepare("SELECT value from rarray(?1);")?;
```
which gives by adjusting your example:
```rust
let stmt = conn.prepare("SELECT id from table_name WHERE id IN (SELECT value from rarray(:things))");
```

**Comment by yaleman** [comment]
I tried that now and got the error: "no such table: rarray", I'm running with  features = ["array", "bundled"] (and tried adding vtab).

**Comment by gwenn** [comment]
> I tried that now and got the error: "no such table: rarray", I'm running with features = ["array", "bundled"] (and tried adding vtab).

I guess you are not using https://docs.rs/rusqlite/latest/rusqlite/vtab/array/fn.load_module.html (like described in the provided example)...

**Comment by gwenn** [comment]
https://sqlite.org/lang_expr.html#the_in_and_not_in_operators
> The right-hand side of an IN or NOT IN operator can be a table name or [table-valued function](https://sqlite.org/vtab.html#tabfunc2) name in which case the right-hand side is understood to be subquery of the form "(SELECT * FROM name)".

So I guess that `SELECT id from table_name WHERE id IN rarray(:things)` should also work

**Comment by yaleman** [comment]
> > I tried that now and got the error: "no such table: rarray", I'm running with features = ["array", "bundled"] (and tried adding vtab).
> 
> I guess you are not using https://docs.rs/rusqlite/latest/rusqlite/vtab/array/fn.load_module.html (like described in the provided example)...

Ah, missed the module load, that seems to be working now, thanks!
