### ISSUE TITLE
Add support for dot commands like `.mode` and `.import`

### ISSUE THREAD

**Issue by stratact** [jgallagher/rusqlite#347]
Currently executing with either commands leads to a panic syntax error. It would be useful to have these, as an example, for importing CSV files with `.mode csv` and `.import <file> <table>` which makes loading the database file a lot faster than doing an INSERT transaction for each row of information. I have to use a helper bash script in my project in order for my app to loader faster when starting up for the first time because of generating a new database file. It would be nice to do this in Rust instead.

**Comment by gwenn** [comment]
You can give a try to the [csv](https://github.com/jgallagher/rusqlite/pull/130/files#diff-b80069e1cbb00d9c32ac62e973eb9141R242) virtual table.
```
CREATE VIRTUAL TABLE vtab USING csv('<file>', HAS_HEADERS);
CREATE TABLE <table> AS SELECT * from vtab;
```

**Comment by gwenn** [comment]
Currently, you have to declare them (not tested):
```
CREATE VIRTUAL TABLE vtab USING csv('<file>', COL1, COL2, COL3, ...);
```
You can also load the [extension](https://www.sqlite.org/cgi/src/artifact/d1e324fac3f87f81) provided by SQLite which generates column names automatically.

**Comment by stratact** [comment]
Using your examples for both, I get the following panic message:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("no such module: csv"))', libcore/result.rs:945:5
```

**Comment by gwenn** [comment]
Sorry,
Virtual table implemented in Rust are not supported by `rusqlite` by default.
1) You must patch or use the [vtab](https://github.com/jgallagher/rusqlite/pull/130) branch.
2) Use the new features: `csvtab` and `vtab`
3) You must load the module before creating the virtual table:
https://github.com/jgallagher/rusqlite/pull/130/files#diff-b80069e1cbb00d9c32ac62e973eb9141R238
```
csvtab::load_module(&db).unwrap();
```

**Comment by stratact** [comment]
Alright, I pointed cargo to your vtab branch.
I added the features to my Cargo.toml.
But, how do I locate the vtab module? I've tried `rusqlite::vtab` and `vtab` and rustc couldn't find it.

**Comment by gwenn** [comment]
Sorry, I forgot the `functions` feature.

**Comment by gwenn** [comment]
I will try to fix this mess: `csvtab` should depend on `vtab` which should depend on `functions` in Cargo file.

**Comment by stratact** [comment]
Thanks, that would be appreciated.

Also just to let you know, I was able to do `csv('<file>', COL1, COL2, COL3, ...)` for creating the vtab with great success. So I've tested it here first :smile:

**Comment by gwenn** [comment]
Thanks for your time/test.
And features have been fixed.

**Comment by bart9h** [comment]
Is there a way to execute the `.schema` command, and get the output text?

**Comment by gwenn** [comment]
`.schema` is a shortcut for `SELECT sql FROM sqlite_master`. So, yes...

**Comment by stratact** [comment]
@gwenn hey there, I did a `cargo update` recently and I noticed it fails to load the csv file into the vtable, did the syntax change?
```rust
thread '<unnamed>' panicked at 'failed to create packages tables for database: SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("illegal argument: \'\'./target/portix_all_packages.csv\'\'"))', libcore/result.rs:945:5
```

**Comment by gwenn** [comment]
Sorry,
The new syntax is the one used by [official](http://www.sqlite.org/cgi/src/finfo?name=ext/misc/csv.c) extension:
```sql
CREATE VIRTUAL TABLE vtab USING csv(
   filename=FILENAME -- Name of file containing CSV content
   [, schema=SCHEMA] -- Alternative CSV schema. 'CREATE TABLE x(col1 TEXT NOT NULL, col2 INT, ...);'
   [, header=YES|NO] -- First row of CSV defines the names of columns if "yes". Default "no".
   [, columns=N] -- Assume the CSV file contains N columns.
   [, delimiter=C] -- CSV delimiter. Default ','.
   [, quote=C] -- CSV quote. Default '"'. 0 means no quote.
);
```
```sql
CREATE VIRTUAL TABLE vtab USING csv(filename='<file>', schema='CREATE TABLE x(col1, col2,...)');
```

**Comment by gwenn** [comment]
a) User uses a `CREATE VIRTUAL TABLE ...` to create a virtual table by using the specified extension/module (ie `csv` here) but does not (at least not directly) specify the column names/types (only the table name is specified here).
b) Internally, the module must call [sqlite3_declare_vtab](sqlite3_declare_vtab) to specify the actual column names/types to SQLite.
The `csv` module can use the headers or the `columns`/`schema` parameters specified in (a).
* if `schema='CREATE TABLE x(cA, cB, ...)'`, column names are `cA`, `cB`, ...,
* if `columns=N` is specified, column names are `c0`...`cN-1`,
* if `headers=yes` is specified, column names are the values of first row,
* else the number of cells in first row is used to generate series `c0`...

So you just have to do step (a).

**Comment by gwenn** [comment]
rusqlite 0.14 released

**Comment by stratact** [comment]
Ah fantastic. Thanks again @gwenn, you're the best!
