### ISSUE TITLE
Commit failure unhandled, database left in unusable state

### ISSUE THREAD

**Issue by kornelski** [jgallagher/rusqlite#366]
When sqlite is used from multiple processes at the same time, `COMMIT` may fail with "database is locked" error.

After that happens, all subsequent transactions in rusqlite fail with "cannot start a transaction within a transaction".

I think this is because:

```rust
    fn commit_(&mut self) -> Result<()> {
        self.committed = true;
        self.conn.execute_batch("COMMIT")
    }
```

Sets `self.committed = true;` without checking whether commit has succeeded, and when `COMMIT` fails, the transaction remains open — forever.

It should probably be: 

```rust
    fn commit_(&mut self) -> Result<()> {        
        self.conn.execute_batch("COMMIT")?;
        self.committed = true;
        Ok(())
    }
```

**Comment by gwenn** [comment]
Random thoughts:
 * either use the `sqlite3_get_autocommit` method and remove the `committed` flag.
 * or do a `rollback` when a COMMIT fails.
