### ISSUE TITLE
How get a field by name?

### ISSUE THREAD

**Issue by mamcx** [jgallagher/rusqlite#372]
All the samples and code I see only allow to get values from rows by position:

`r.get(0)`

But how if I wanna get the list of columns (name, type) and get by name like:

`r.name("id")`

My use-case is turn the row into a HashMap of <names, value>, like is common in other databases libs.

**Comment by gwenn** [comment]
[Rows.get](https://docs.rs/rusqlite/0.13.0/rusqlite/struct.Row.html#method.get) takes a [RowIndex](https://docs.rs/rusqlite/0.13.0/rusqlite/trait.RowIndex.html) which is implemented by `i32` but also by `&str`...
So, you can do:
```
r.get("id")
```

**Comment by mamcx** [comment]
Oh, great. And is possible to get the list of columns/types returned?

**Comment by mamcx** [comment]
Ok, this look good but I having trouble understanding how get the column names and the values:

```
fn select(of:&SqliteDb, sql:&str, params:Option<DbRow>) -> RowResult {
    let mut stmt = of.conn.prepare(sql)?;
    let names = stmt.column_names(); //<-- HERE

    let mut result = stmt.query(&[])?;

    let mut rows = Vec::new();

    while let Some(value) = result.next() {
        let mut row = DbRow::new();
        for name in names {
            row.insert(name.to_string(), Scalar::None);
        }
        rows.push(row)
    }

    Ok(rows)
}
```

I get 

> 16 |     let names = stmt.column_names(); //<-- This
>    |                 ---- immutable borrow occurs here
> 17 |
> 18 |     let mut result = stmt.query(&[])?;
>    |                      ^^^^ mutable borrow occurs here

Now, I understand what is happening but how solve it?

**Comment by gwenn** [comment]
I am afraid you have to duplicate `names`.

**Comment by mamcx** [comment]
Apply stmt.column_names().clone() not make the problem disappear.

**Comment by gwenn** [comment]
```rust
    let names = stmt.column_names().into_iter().map(|s| String::from(s)).collect::<Vec<_>>();
    let mut rows = stmt.query(&[]).unwrap();

    let mut values = Vec::new();
    while let Some(row) = rows.next() {
        let row = row.unwrap();
        for name in names.iter() {
            values.push((name.clone(), row.get::<_, Value>(name.as_ref())));
        }
    }
    println!("{:?}", values);
```
