### ISSUE TITLE
Errors building bundle with stable-x86_64-pc-windows-gnu toolchain

### ISSUE THREAD

**Issue by spease** [jgallagher/rusqlite#375]
```
C:\Users\spease\dev\rust\pmi_rust\target\debug\deps\liblibsqlite3_sys-3394c717ad5d2eb8.rlib(sqlite3.o): In function `winGetTempname':
/c/Users/spease/.cargo/registry/src/github.com-1ecc6299db9ec823/libsqlite3-sys-0.9.1/sqlite3/sqlite3.c:42278: undefined reference to `cygwin_conv_path'
/c/Users/spease/.cargo/registry/src/github.com-1ecc6299db9ec823/libsqlite3-sys-0.9.1/sqlite3/sqlite3.c:42284: undefined reference to `__errno'
C:\Users\spease\dev\rust\pmi_rust\target\debug\deps\liblibsqlite3_sys-3394c717ad5d2eb8.rlib(sqlite3.o): In function `winFullPathname':
/c/Users/spease/.cargo/registry/src/github.com-1ecc6299db9ec823/libsqlite3-sys-0.9.1/sqlite3/sqlite3.c:43005: undefined reference to `cygwin_conv_path'
/c/Users/spease/.cargo/registry/src/github.com-1ecc6299db9ec823/libsqlite3-sys-0.9.1/sqlite3/sqlite3.c:43009: undefined reference to `__errno'
/c/Users/spease/.cargo/registry/src/github.com-1ecc6299db9ec823/libsqlite3-sys-0.9.1/sqlite3/sqlite3.c:43027: undefined reference to `cygwin_conv_path'
/c/Users/spease/.cargo/registry/src/github.com-1ecc6299db9ec823/libsqlite3-sys-0.9.1/sqlite3/sqlite3.c:43031: undefined reference to `__errno'
```

Cargo.toml
```
libsqlite3-sys = { version = "0.9.1", features = ["bundled"] }
```

Everything previously worked fine with the stable-x86_64-pc-windows-msvc toolchain. For GCC, I'm using the gcc package from Pacman from msys2 20180531 via Chocolatey.

**Comment by gwenn** [comment]
You should try to compile SQLite directly: `gcc sqlite3.c`.
I guess you will have the same errors.
Which means errors are not related to `rusqlite`...

**Comment by spease** [comment]
Not sure when if ever that I'm going to get back to this. You could very well be right though.

**Comment by gwenn** [comment]
Would you mind closing the issue ?

**Comment by drewkett** [comment]
For anyone who comes across this, you need to use the mingw64 version of gcc (`pacman -S mingw-w64-x86_64-gcc`). `pacman -S gcc` installs the msys version which effectively is an updated Cygwin which is why the Cygwin version of SQLite is compiled using this compiler but rust doesn't have any Cygwin symbols to link against so the final linking in rust fails.

**Comment by sharkbound** [comment]
@drewkett 
Iv'e been having this exact same issue.
Also, confirmed that rust is using `x86_64-w64-mingw32-gcc` [version 11.3.0-1] (from cygwin).

However, i still get this linking error. 
I'm pretty new to linking errors as rust is my first time seriously trying to solve one.

Not sure if you would have any recommendations or not, but there is very little resources i can find for fixing this particular error.
