### ISSUE TITLE
`array` feature should not require `bundled`

### ISSUE THREAD

**Issue by thomcc** [jgallagher/rusqlite#384]
This prevents using the `array` in conjunction with the `sqlcipher` feature, for example.

**Comment by gwenn** [comment]
But `array` depends on [Pointer Passing Interfaces](https://sqlite.org/bindptr.html).
And I would prefer not add a `min_sqlite_version_3_20_0` feature...
I will try to fix the CI build scripts.

**Comment by gwenn** [comment]
Should be fixed now in `master` branch.
