### ISSUE TITLE
Error in SqliteFailure not exported

### ISSUE THREAD

**Issue by kornelski** [jgallagher/rusqlite#398]
I'm trying to check whether an error I get from rusqlite is caused by database being locked, but it seems that the error type necessary for this check isn't quite public (it's not clickable in Rustdoc output, and I can't see its full name):

https://jgallagher.github.io/rusqlite/rusqlite/enum.Error.html#variant.SqliteFailure

I guess the error is public, but from another crate, which would require me to find that crate, add it to my project with a matching version, just to be able to name this type in `match`.

Could you publicly re-export this type?

**Comment by gwenn** [comment]
Sorry,
The doc at https://jgallagher.github.io/rusqlite/rusqlite/ is not up to date.
You should use https://docs.rs/rusqlite/0.14.0/rusqlite/enum.Error.html#variant.SqliteFailure.
```rust
extern crate libsqlite3_sys as ffi;
extern crate rusqlite;

use rusqlite::Connection;
use rusqlite::Error::SqliteFailure;

    if let Err(e) = Connection::open_in_memory() {
        if let SqliteFailure(rc, _) = e {
            println!("{:?}", rc);
            if rc.code == ffi::ErrorCode::DatabaseLocked {
                println!("{:?}", rc.extended_code);
            }
        }
    }
```

**Comment by gwenn** [comment]
Should I delete [gh-pages](https://github.com/jgallagher/rusqlite/tree/gh-pages) ?

**Comment by kornelski** [comment]
Deleting of outdated gh-pages would help (I looked at gh pages documentation, because some projects prefer them when docs.rs can't build the crate properly).

I've found the error code is re-exported, but AFAIK I'd still need `extern crate libsqlite3_sys` to `match` against error type.

**Comment by gwenn** [comment]
Ah, right.
I think you don't have to use `extern crate libsqlite3_sys`.
```rust
use rusqlite::Error::SqliteFailure;
use rusqlite::ErrorCode;

    if let Err(e) = Connection::open_in_memory() {
        if let SqliteFailure(rc, _) = e {
            println!("{:?}", rc);
            if rc.code == ErrorCode::DatabaseLocked {
                println!("{:?}", rc.extended_code);
            }
        }
    }
```

**Comment by gwenn** [comment]
Could you please confirm that the following example works as expected:
```rust
extern crate rusqlite;

use rusqlite::Connection;
use rusqlite::Error::SqliteFailure;
use rusqlite::ErrorCode;
use rusqlite::OpenFlags;

fn main() {
    if let Err(e) = Connection::open_with_flags("test.db", OpenFlags::SQLITE_OPEN_READ_ONLY) {
        if let SqliteFailure(rc, _) = e {
            println!("{:?}", rc);
            if rc.code == ErrorCode::DatabaseLocked {
                println!("{:?}", rc.extended_code);
            }
        }
    } else {
        println!("OK");
    }
}
```
?
And close this issue accordingly.

**Comment by kornelski** [comment]
It does.

**Comment by jimis** [comment]
It would be nice to document such an example, it's not obvious how one can isolate the `code` enum. I'm glad I found this example here.
