### ISSUE TITLE
Impossible to execute a pragma in 0.14.0

### ISSUE THREAD

**Issue by peterholak** [jgallagher/rusqlite#400]
In 0.14.0, it is impossible to execute `PRAGMA journal_mode=WAL`.

When using `query_row`, it says that query is not read-only (https://github.com/jgallagher/rusqlite/commit/31de0187a257ed7443e5bc54ed0657fecdaf7879). When using `execute`, it says that the query returns results (https://github.com/jgallagher/rusqlite/issues/273). 

Using bundled sqlite.

**Comment by gwenn** [comment]
Sorry,
`conn.execute_batch` should be used if you don't care of the result.
I will try to fix this bug (or rollback 31de018) by doing the check only if the query returns no row.

**Comment by gwenn** [comment]
https://sqlite.org/pragma.html#pragma_journal_mode
> If the journal mode could not be changed, the original journal mode is returned.
So `query_row` is the right way but cannot be used with 0.14.0.

**Comment by gwenn** [comment]
rusqlite 0.15 released
