### ISSUE TITLE
Statement::query doesn't accept empty lists

### ISSUE THREAD

**Issue by njaard** [jgallagher/rusqlite#424]
As of 0.15, one can't use this kind of code:

    let mut stmt = db.prepare(...);
    stmt.query(&[]);

because type inference can't work on the `&[]`.

There's no clear way to resolve this problem for a user.

**Comment by njaard** [comment]
It seems to not accept heterogeneous types, also:

> 130 |   stmt.execute(&[domain, format!("{}", today).as_str(), bytes]).unwrap();            
>    |                                                         ^^^^^ expected &str, found struct `std::vec::Vec`

**Comment by gwenn** [comment]
When parameters have different types, you need to force the type of the first one.
Something like:
```
stmt.execute(&[domain &ToSql, format!("{}", today).as_str(), bytes]).unwrap();
```

**Comment by gwenn** [comment]
Would you mind closing the issue ?

**Comment by njaard** [comment]
I actually think the situation isn't usable right now, but ok.

**Comment by gwenn** [comment]
Maybe we should ask for help ?
For example, we can ask: why https://github.com/sfackler/rust-postgres/issues/265 is still open ?

**Comment by mqudsi** [comment]
@gwenn I've read the linked discussions and code, but I'm not clear on why this became required? What new feature or bugfix caused the compiler to no longer be able to infer the type when providing an unadorned `&[]` as the argument?

**Comment by gwenn** [comment]
With rusqlite < 0.15, SQL parameters can only be passed using `&[&ToSql]`.
If you have a `Vec<String>` or a `Vec<i32>`, you cannot used it directly (see https://github.com/jgallagher/rusqlite/issues/312 and https://github.com/jgallagher/rusqlite/pull/409).
Now (rusqlite >= 0.15), you can use anything which can be transformed into an iterator of `ToSql` items.
The drawback is you cannot use `&[]` when there is no param.

**Comment by mqudsi** [comment]
Thanks.
