### ISSUE TITLE
libsqlite3-sys: Doesn't find libsqlite3.so in /usr/local/bin

### ISSUE THREAD

**Issue by kpcyrd** [jgallagher/rusqlite#429]
I'm on openbsd and noticed libsqlite3-sys is not able to detect the library from the sqlite3 package, the build just fails with `ld: cannot find -lsqlite3`

I'm able to build regardless with `SQLITE3_LIB_DIR=/usr/local/lib cargo build`

pkg-config is able to pick it up:
```
$ pkg-config --libs sqlite3
-L/usr/local/lib -lsqlite3
```

**Comment by gwenn** [comment]
Could you please try to tweak this line:
https://github.com/jgallagher/rusqlite/blob/master/libsqlite3-sys/build.rs#L133
```
            .print_system_libs(false)
```
Or try to trace the error:
https://github.com/jgallagher/rusqlite/blob/master/libsqlite3-sys/build.rs#L144
```
            Err(e) => {
                eprintln!("{:?}", e);
                // ...
            }
```
?

**Comment by kpcyrd** [comment]
This seems to be my fault. I was trying to figure out all dependencies needed by trail and error so /usr/local/lib/libsqlite3* didn't exist while libsqlite3-sys was building.

It seems the pkg-config results are cached until libsqlite3-sys is rebuilt.

Sorry for the noise.
