### ISSUE TITLE
the trait `rusqlite::types::ToSql` is not implemented for `std::vec::Vec<&std::string::String>`

### ISSUE THREAD

**Issue by bdrung** [jgallagher/rusqlite#430]
I want to construct a SQL query that uses an `in` condition on an input vector. The simplified code snippet looks like:
```rust
let values: Vec<String> = vec!["foo".to_string(), "bar".to_string()];
let mut stmt = try!(conn.prepare("SELECT * FROM table where command in ?"));
let rows = try!(stmt.query_map(&[values], ...));
```
I expect that the constructed SQL look like:
```sql
SELECT * FROM table where command in ('foo', 'bar')
```
But compiling the code fails with
```
the trait `rusqlite::types::ToSql` is not implemented for `std::vec::Vec<&std::string::String>`
```

Is this something that rusqlite should support or should this use case be covered in the application? I just started learning Rust (by rewriting command-not-found in Rust) and are open to suggestions how to implement that.

**Comment by gwenn** [comment]
You should pass the vector directly:
```
let rows = try!(stmt.query_map(values, ...));
```

A complete example:
```rust
use rusqlite::Connection;

fn main() {
    let db = Connection::open_in_memory().unwrap();

    let values: Vec<String> = vec!["foo".to_string(), "bar".to_string()];
    db.query_row("SELECT ?, ?",
                 values, // <======
                 |row| {
                     let foo: String = row.get(0);
                     let bar: String = row.get(1);
                    println!("{}, {}", foo, bar);
                 }).unwrap();
}
```

**Comment by bdrung** [comment]
The problem is that the length of the vector is dynamic.

**Comment by gwenn** [comment]
In that case, you can give `array` extension a try.
Currently, only vector of `Value` are supported (`String`s can be transformed into `Value`s).
See https://github.com/jgallagher/rusqlite/blob/master/src/vtab/array.rs#L186
And https://sqlite.org/carray.html

```rust
let mut stmt = try!(conn.prepare("SELECT * FROM table where command in rarray(?)"));
```

**Comment by gwenn** [comment]
Would you mind closing the issue ?

**Comment by bdrung** [comment]
I still haven't found time to try out the array extension. I'll close this issues now and will report back in an error case. Thanks for your help.

**Comment by i-schuetz** [comment]
Too bad this discussion was discontinued. How to perform `in` query with a `Vec`? I'm also getting the "is not implemented" error.

**Comment by gwenn** [comment]
https://github.com/rusqlite/rusqlite/blob/master/src/vtab/array.rs#L18
>      // Note: A `Rc<Vec<Value>>` must be used as the parameter.
...

**Comment by i-schuetz** [comment]
@gwenn Thanks! I also wasn't using the `vtab` and `array` features.

Just one question more, as it's a bit difficult to understand from the source, when can the result of `rusqlite::vtab::array::load_module(&db)` be `Err`? If I'm sure that the features are enabled, can I assume it's always `Ok`?

**Comment by gwenn** [comment]
The error comes from [sqlite3_create_module_v2](http://sqlite.org/c3ref/create_module.html).
But SQLite documentation doesn't say anything about the returned code !
So you should assume that `load_module` can fail.

**Comment by i-schuetz** [comment]
Ok, thanks again!
