### ISSUE TITLE
DateTime doesn't parse correctly for chrono

### ISSUE THREAD

**Issue by jasonszhao** [jgallagher/rusqlite#433]
Related to #431, but for the `chrono` crate, instead of the `time` crate. Also, here we're going from less to more information. 

When parsing a SQLite text column created with `date('now')` into a `chrono::DateTime<Utc>`, I get the error: 

    Conversion error from type Text at index: 3, premature end of input. 

Workaround is to always use the `datetime()` SQLite function, and never `date()`. 

Not sure if this is a bug or intentional.

**Comment by gwenn** [comment]
`SELECT date('now'), CURRENT_DATE;` <=> `chrono::NaiveDate`
`SELECT time('now'), CURRENT_TIME;`<=> `chrono::NaiveTime`
`SELECT datetime('now'), CURRENT_TIMESTAMP` <=> `chrono:NaiveDateTime` or `chrono:: DateTime`

**Comment by jasonszhao** [comment]
I guess the current behavior of returning `Err(e)` makes sense then. [SQLite has only five types](https://www.sqlite.org/datatype3.html), so it's up to application code to enforce more refined formats, such as dates. Rusqlite (like other Rust libraries, I've noticed) chooses to be rigid and less forgiving in its enforcement.
