### ISSUE TITLE
libsqlite3-sys and all its dependents get recompiled whenever I switch between `cargo b` and `cargo watch -x b`

### ISSUE THREAD

**Issue by Boscop** [jgallagher/rusqlite#435]
When I build my crate (only whenever I switch between `cargo b` and `cargo watch -x b`!), it always recompiles a few deps that didn't change (starting with `libsqlite3-sys`):
```
   Compiling libsqlite3-sys v0.9.3
   Compiling diesel v1.3.3
   Compiling migrations_internals v1.3.0
   Compiling r2d2-diesel v1.0.0
   Compiling migrations_macros v1.3.0
   Compiling diesel_migrations v1.3.0
```
And then it recompiles my workspace's `db` crate that uses diesel, and all the other crates that depend on the `db` crate, so somehow `libsqlite3-sys` gets marked as dirty, but why?

It definitely didn't happen before I upgraded from diesel 0.16 (which used `libsqlite3-sys 0.8.1`) to diesel 1.3 (last week).
Do you have any idea what could cause this?

Maybe `libsqlite3-sys 0.9.3` is reading some environment variables that are different with [`cargo-watch`](https://github.com/passcod/cargo-watch), and these env vars were not used in `libsqlite3-sys 0.8.1`?

**Comment by Boscop** [comment]
It's still happening, whenever I switch between `cargo b` and `cargo watch -x b`, any idea why?

**Comment by gwenn** [comment]
@Boscop Could you please check #627 ?
Thanks.

**Comment by Boscop** [comment]
@gwenn Yes, that fixes it. Thanks so much!
