### ISSUE TITLE
Does this library support Android and iOS

### ISSUE THREAD

**Issue by hajsf** [jgallagher/rusqlite#437]
Hi..
I build my first "Hello-World" Flutter/Rust app that run smoothly with Android and iOS, I need to dive deeper, I know flutter already has [sqlite plugin](https://pub.dartlang.org/packages/sqflite), but I want to try it with native code using rust.

What is the first step to be followed here, as seen in flutter, the first step is finding the location of the DataBase path: 

```
// Get a location using getDatabasesPath
var databasesPath = await getDatabasesPath();
String path = join(databasesPath, "demo.db");
```

Is there something similar with this library?

**Comment by gwenn** [comment]
Sorry, I don't know.
I hope someone else can reply.

**Comment by Dushistov** [comment]
> Is there something similar with this library?

I use this library on Android. It works in the same way as on Linux/Mac OS X/Windows.
So all examples from documentation you can run on PC and on Android.
I didn't try rusqlite on iOS.

**Comment by hajsf** [comment]
Thanks @Dushistov,
Can you help with [this](https://github.com/jgallagher/rusqlite/issues/443#issue-390814465) error I just got while compiling for Android.
