### ISSUE TITLE
Callbacks must not be able to unwind into sqlite code

### ISSUE THREAD

**Issue by jonas-schievink** [jgallagher/rusqlite#439]
Unwinding across an FFI boundary is undefined behaviour, and thus must not be possible using safe Rust code. The implementation of `Connection::busy_handler` looks like this:

https://github.com/jgallagher/rusqlite/blob/52607646dcd847d1da69e93c575dbff6eabb348f/src/busy.rs#L48-L65

If the user-provided callback panics, the panic may unwind out of `busy_handler_callback` and into sqlite, which is undefined behaviour. To fix that, every single user-supplied callback that ends up getting called by sqlite must be protected by putting it inside [`catch_unwind`](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html).

**Comment by gwenn** [comment]
And:
* `config_log`
* `trace`
* `profile`
* `commit_hook`
* `rollback_hook`
* `update_hook`
* `sqlite3_bind_pointer` and `free_array` ?
* `wait_for_unlock_notify` ?
* vtab

**Comment by gwenn** [comment]
https://github.com/rust-lang/rust/pull/55982 ?

**Comment by jonas-schievink** [comment]
Indeed that would fix the unsoundness, but I don't recommend waiting for it to land, nor is aborting necessarily the right thing to do here - for example `rlua` allows transferring panics through Lua code and resuming them when control is returned back to Rust, which might be a better choice here as well.
