### ISSUE TITLE
Trait is unsafe to implement as panics in it's methods lead to undefined behaviour.

### ISSUE THREAD

**Issue by rustonaut** [jgallagher/rusqlite#440]
https://github.com/jgallagher/rusqlite/blob/52607646dcd847d1da69e93c575dbff6eabb348f/src/functions.rs#L190-L209

The methods of the trait are called in C-callbacks and panicking there would be unwind into C
which is unsafe and undefined behavior. 

The callbacks should either use `std::panic::catch_unwind` or the trait should be `unsafe`
to implement. The former seems better as when abort on panic is used `catch_unwind` should
not induce any overhead.

The places where the callbacks are made unsafely are here:
- https://github.com/jgallagher/rusqlite/blob/52607646dcd847d1da69e93c575dbff6eabb348f/src/functions.rs#L395
- https://github.com/jgallagher/rusqlite/blob/52607646dcd847d1da69e93c575dbff6eabb348f/src/functions.rs#L403
- https://github.com/jgallagher/rusqlite/blob/52607646dcd847d1da69e93c575dbff6eabb348f/src/functions.rs#L434

All in some `extern "C" fn` passed in as a callback to sqlite.

**Comment by rustonaut** [comment]
Related: https://github.com/jgallagher/rusqlite/issues/439

**Comment by gwenn** [comment]
Should be fixed with 0.16.0 release.
