### ISSUE TITLE
No way to get a `rusqlite::Connection` from a `*mut libsqlite3_sys::sqlite3`

### ISSUE THREAD

**Issue by thomcc** [jgallagher/rusqlite#453]
I'd like to write a sqlite extension in rust that loads functions into a connection using rusqlite. I can't do this because I can't get an rusqlite::Connection from the sqlite3 pointer.

Ideally there would be an (unsafe) function for doing this (and presumably I'd need to mem::forget(conn) before sqlite3_extension_init returns...)

**Comment by gwenn** [comment]
Could you please give PR #456 a try ?

**Comment by thomcc** [comment]
My original goal is unworkable due to how the sqlite extension API works (it passes you a pointer to a structure that contains all the methods you're allowed to call -- e.g. instead of sqlite3_create_function_v2, i'd have to call api_ptr.create_function_v2, see https://github.com/cloudmeter/sqlite/blob/master/sqlite3ext.h#L218 for what I mean).

So this can be closed. Merge the PR if you want

**Comment by gwenn** [comment]
@thomcc Are you sure ?
For me, you have access to both: `sqlite3` and `sqlite3_api_routines`.
https://sqlite.org/loadext.html
```
int sqlite3_extension_init(
  sqlite3 *db, 
  char **pzErrMsg, 
  const sqlite3_api_routines *pApi
){
```
https://github.com/gwenn/sqlite-csv-ext/blob/master/csv.c#L748
https://github.com/gwenn/sqlite-regex-replace-ext/blob/master/glib_replace.c#L77

**Comment by thomcc** [comment]
Pretty sure, you can call functions so long as the sqlite3 versions match up, otherwise you get segfaults.

Ehhh, I guess that limitation is actually acceptable for my use case though, now that I think about it, although it's annoying (due to us using sqlcipher and sqlite somewhat interchangeably)

**Comment by gwenn** [comment]
rusqlite 0.17 released
