### ISSUE TITLE
borderline case: statement parameter indices may have gap(s)

### ISSUE THREAD

**Issue by gwenn** [jgallagher/rusqlite#457]
```sql
SELECT * FROM foo where col = ?2;
```
[sqlite3_bind_parameter_count](https://www.sqlite.org/c3ref/bind_parameter_count.html)
> If parameters of the ?NNN form are used, there may be gaps in the list.

**Comment by thomcc** [comment]
I suspect this could be handled by letting the user specify parameters separate from executing the query.

(Which would also allow things like binding some parameters by position and others by name, which is something I've definitely wanted to do before).
