### ISSUE TITLE
Expose sqlite3_changes()

### ISSUE THREAD

**Issue by theduke** [jgallagher/rusqlite#460]
I don't currently see a way to get the information exposed by [sqlite_changes()](https://www.sqlite.org/c3ref/changes.html).

Would be very valuable to have this.

**Comment by gwenn** [comment]
You mean [sqlite3_changes](https://github.com/jgallagher/rusqlite/blob/master/src/lib.rs#L1021) ?

**Comment by gwenn** [comment]
@theduke Should I rollback the fix ?

**Comment by theduke** [comment]
Ah, @gwenn , I hadn't noticed the return value!

That indeed makes this unnecessary.
