### ISSUE TITLE
Support for sqlite3_db_config

### ISSUE THREAD

**Issue by thomcc** [jgallagher/rusqlite#468]
The design sqlite3_db_config is weird, hard to do in a general purpose way, and some of them are definitely unsafe.

Specifically, the only part I care about is [`SQLITE_DBCONFIG_TRIGGER_EQP`](https://www.sqlite.org/c3ref/c_dbconfig_defensive.html#sqlitedbconfigtriggereqp).

**Comment by thomcc** [comment]
Probably the former, since many of them take different numbers/types of arguments, unfortunately.

Although, the ones that are safe are probably all/mostly just the boolean flags (I think you could expose SQLITE_DBCONFIG_MAINDBNAME version safely, so long as you leaked the string you pass to it, but SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION is probably unsafe to turn on, even though it is just a flag).

That said, I only really care about TRIGGER_EQP (and maybe ENABLE_QPSG in the future, although not concretely).

**Comment by gwenn** [comment]
Could you please give PR #475 a try ?
