### ISSUE TITLE
Thread safe Connection and Optimisation

### ISSUE THREAD

**Issue by gwenn** [jgallagher/rusqlite#49]
Hello,
It seems that Rust ensures that only one thread can use a Connection at the same time.
If it is true, the following optimisation can be applied when a connection is opened:
http://sqlite.org/threadsafe.html
> Multi-thread. In this mode, SQLite can be safely used by multiple threads provided that no single database connection is used simultaneously in two or more threads.
> The SQLITE_OPEN_NOMUTEX flag causes the database connection to be in the multi-thread mode.

```diff
-        let flags = SQLITE_OPEN_READ_WRITE | SQLITE_OPEN_CREATE;
+        let flags = SQLITE_OPEN_READ_WRITE | SQLITE_OPEN_CREATE | SQLITE_OPEN_NO_MUTEX;
```
Regards.

**Comment by jgallagher** [comment]
Closed by #50. Thanks!
