### ISSUE TITLE
With version 0.17 there is no way to return custom errors from handlers of query_map*

### ISSUE THREAD

**Issue by twistedfall** [jgallagher/rusqlite#493]
Hi,

In version 0.17 you introduced the change for `query_map()` and `query_map_named()` to take handlers that must return `Result`. The problem I'm running into is that `Result`'s error type is forced to be `rusqlite::Error` and I need to return other error types from that handler. Will you be able to make the error type generic? Or maybe adding a `Custom` enum for `rusqlite::Error`?

Regards!

**Comment by thomcc** [comment]
I haven't followed the 0.17.0 changes very closely (and have not updated my code to use it yet), so maybe this has changed, but I believe that query_and_then is the method you should use, and not query_map.

It requires that a rusqlite::Error can be converted into your error type, but generally this is not a problem.

**Comment by gwenn** [comment]
Indeed, callback signature has been changed.
Before: `F: FnMut(&Row<'_, '_>) -> T`
After:    `F: FnMut(&Row<'_>)     -> Result<T>`
Because, now, `Row.get` does not unwrap/panic.
As suggested by @thomcc, you should try `query_and_then`.

**Comment by Dushistov** [comment]
@gwenn 

What about `query_row` (for some reason there is `query_row_and_then` for `Connection`, but there is no for `Statement`, only `rusqlite::Statement::query_row` exists)?

**Comment by Dushistov** [comment]
@gwenn 

And for some reason `rusqlite::Error: std::convert::From<rusqlite::types::FromSqlError>` is not satisfied (I try to use `ValueRef::as_blob` inside `query_row`

**Comment by gwenn** [comment]
I guess you want:
```rust
x.query_row(param, |r| r.get::<_, Vec<u8>(0))
```
`get::<_, Vec<u8>>` uses `ValueRef::as_blob` and do the conversion from `FromSqlError` to `Error`.

**Comment by Dushistov** [comment]
> x.query_row(param, |r| r.get::<_, Vec<u8>>(0))

In fact I want opposite thing, do not create `Vec<u8>`.
```
stmt.query_row(params![track_id], |row| {
            let blob: ValueRef = row.get_raw_checked(0)?;
            let blob: &[u8] = blob
                .as_blob()
                .map_err(|err| sql_conv_failure_err(err, 0, rusqlite::types::Type::Blob))?;
            let decoded: NavEvent = bincode::deserialize(blob)
                .map_err(|err| sql_conv_failure_err(err, 0, rusqlite::types::Type::Blob))?;
            Ok(decoded)
        })?;

fn sql_conv_failure_err<Err>(err: Err, idx: usize, tpy: rusqlite::types::Type) -> rusqlite::Error
where
    Err: std::error::Error + Send + Sync + 'static,
{
    rusqlite::Error::FromSqlConversionFailure(idx, tpy, Box::new(err))
}
```

it is really inconvenient that there is no `query_row_and_then`

**Comment by gwenn** [comment]
Ok, something like that:
https://github.com/jgallagher/rusqlite/pull/498/files#diff-0abac89395fa2aa6a7cc74b660bc4744R935
?

**Comment by Dushistov** [comment]
> Ok, something like that:
> https://github.com/jgallagher/rusqlite/pull/498/files#diff-0abac89395fa2aa6a7cc74b660bc4744R935

```Rust
 r.get_raw_checked(0)?
                .as_blob()
                .map_err(|err| Error::from_column(err, 0, Type::Blob))
```

Not sure, I would be fond of something for get rid of `map_err` completely.
If for some reason `Statement::query_row_and_then` is impossible to implement,
then why not remove `Type::Blob`? 
Obviously `as_blob()` should remove something about blob error,
may be it is possible to hide `Type` info inside `FromSqlError`,
also may be `ValueRef` hold info about column number, then it would be nice also hide this info inside `FromSqlError`.

**Comment by gwenn** [comment]
`Statement::query_row_and_then` is not impossible to implement but you can already use `Statement::query_row` (+ `Result::map_err`) + `Result::and_then`.

Is there any reason why you don't implement `FromSql` for `NavEvent` ? Orphan rules ?

**Comment by Dushistov** [comment]
> but you can already use Statement::query_row (+ Result::map_err) + Result::and_then

When inside closure inside of `Statement::query_row` you have to write `map_err` instead of `?`,
this is not neat, but not bad. But when I need write the similar stuff in 4 other places this is bad.

In case of `query_row_and_then` I can write:
```Rust
stmt.query_row_and_then(params![track_id], |row| {
            let blob: ValueRef = row.get_raw_checked(0)?;
            let decoded: NavEvent = bincode::deserialize(blob.as_blob()?);
            Ok(decoded)
        })?;
```

And that's all. 

> Is there any reason why you don't implement FromSql for NavEvent

I convert blob to NavEvent only in one place, in other places I convert blob->another types.
So it would be just more code if I add `impl FromSql` in compare with call of `query_row`.

**Comment by twistedfall** [comment]
> I believe that query_and_then is the method you should use, and not query_map.

Thank you, that's exactly what I needed, somehow I missed it. I'm closing this issue, if there are still some unresolved topics, please create a new one.
