### ISSUE TITLE
How get the field type for a null field?

### ISSUE THREAD

**Issue by mamcx** [jgallagher/rusqlite#494]
Related to https://github.com/jgallagher/rusqlite/issues/372.

I can query a `Value` for the type, but if the field allow null, and the data return null, the original type is lost.

I can get the column names, but not the types.

**Comment by thomcc** [comment]
I'm not sure this makes sense. NULL values in SQLite don't have a type besides NULL. SQLite's type system can be a bit strange, so you might want to read over https://www.sqlite.org/datatype3.html.

**Comment by mamcx** [comment]
Yeah, I know.

But the field have:

```sql
CREATE TABLE config (
    config_id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    value TEXT NOT NULL
);
```
Now If I do:

```sql
SELECT * FROM config;
```

I need to know that `value` is `Text`.

**Comment by gwenn** [comment]
Currently, there is no helper to access metadata:
 * [`sqlite3_column_decltype`](http://sqlite.org/c3ref/column_decltype.html)
 * or/and [`table_info`](https://sqlite.org/pragma.html#pragma_table_info)

**Comment by gwenn** [comment]
In `postgres` crate:
 * [Statement.columns](https://docs.rs/postgres/0/postgres/stmt/struct.Statement.html#method.columns)
 * [Rows.columns](https://docs.rs/postgres/0/postgres/rows/struct.Rows.html#method.columns)

**Comment by mamcx** [comment]
Yes, that is what is expected.

**Comment by gwenn** [comment]
Fixed by 0.18 release.

**Comment by billop** [comment]
Is it currently possible to get more metadata, such as which columns are nullable? `columns` seems to only give declared type without that kind of extra information.

**Comment by gwenn** [comment]
If you want such information, you have to use:
1. [sqlite3_column_origin_name](http://sqlite.org/c3ref/column_database_name.html) => `col_name` or `null` for expression
2. [sqlite3_column_table_name](http://sqlite.org/c3ref/column_database_name.html) => `tbl_name` or `null` for expression
3. [sqlite3_column_database_name](http://sqlite.org/c3ref/column_database_name.html) => `db_name` or `null` for expression
And then:
```sql
sqlite> SELECT "notnull" FROM <db_name>.pragma_table_info('<tbl_name>') WHERE name like '<col_name>';
```
Currently, there is no such feature in `rusqlite`. We can add such information behind a new 'metadata' feature.

**Comment by billop** [comment]
So is it just impossible right now? I've been trying to use queries but it looks like they basically only return rows. I can't figure out how to run something like `sqlite> SELECT "notnull" FROM <db_name>.pragma_table_info('<tbl_name>') WHERE name like '<col_name>';` and get its result.

**Comment by gwenn** [comment]
@billop There is already [this](https://github.com/jgallagher/rusqlite/blob/master/src/pragma.rs#L385) test which works fine !

**Comment by billop** [comment]
Unless I'm doing something wrong, it looks like there's no way of accessing the "notnull" column.

```rust
conn.prepare(r#"SELECT "notnull" FROM books.pragma_table_info("books")"#)?;
```

Results in InvalidColumnType error with `row.get(0)`.

```rust
conn.prepare(r#"SELECT * FROM books.pragma_table_info("books")"#)?;
```

Also results in InvalidColumnType with `row.get(3)`.

The actual output that I get:

```rust
Err(
    rusqlite::Error(
        InvalidColumnType(
            0,
            "notnull",
            Integer,
        ),
    ),
)
```

**Comment by billop** [comment]
Thanks for the help, I basically got it working:

```rust
    fn get_nullable_stats(self: Self) -> Result<Vec<i64>, Error> {
        let conn = self.connect()?;
        let mut table_info =
            conn.prepare(r#"SELECT "notnull" FROM books.pragma_table_info("books")"#)?;
        let mut columns = Vec::new();
        let mut rows = table_info.query(NO_PARAMS)?;

        dbg!(rows.columns());

        while let Some(row) = rows.next()? {
            let row = row;
            let column: i64 = row.get(0)?;
            columns.push(column);
        }

        Ok(columns)
    }
```

**Comment by gwenn** [comment]
@billop You can also return booleans:
```rust
fn get_nullable_stats(self: Self) -> Result<Vec<bool>, Error> {
...
            let column: bool = row.get(0)?;
```
