### ISSUE TITLE
Should `Box<dyn ToSql>` be an instance of `ToSql`?

### ISSUE THREAD

**Issue by DevJac** [jgallagher/rusqlite#500]
I had a function like `fn my_value_to_sql(v: &MyValue) -> Box<dyn ToSql>` which would parse a `MyValue` into one of several different types, but all the types implemented `ToSql`. I had to returned this `Box`ed since otherwise the size of the return value wouldn't have been known.

It would have been nice if `Box<dyn ToSql>` was an instance of `ToSql`.

(I'm fairly new to Rust, so it may be that my `Box` approach is misguided, but it's the best I could come up with.)

**Comment by thomcc** [comment]
Returning a `&dyn ToSql` definitely should work (and will be more efficient than using a Box, although will impose more lifetime restrictions). I'd expect Box<dyn ToSql> to work too, but since i know `Box<dyn Error>` doesn't implement std::error::Error, I could believe that I'm wrong.

**Comment by DevJac** [comment]
You sure? `ToSql` is a trait; `&dyn ToSql` can be any of an infinite number of types. How can its size be known? Or am I mistaken that the size of a returned value must be known?
