### ISSUE TITLE
Android: during bundled compile, cannot find aarch64-linux-android-clang

### ISSUE THREAD

**Issue by smokytheangel0** [jgallagher/rusqlite#503]
my ~/.cargo/config is the following:
`
[target.aarch64-linux-android]
ar = "/Users/j/Desktop/SDKs/android/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android-ar"
linker = "/Users/j/Desktop/SDKs/android/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android28-clang"

[target.armv7-linux-androideabi]
ar = "/Users/j/Desktop/SDKs/android/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-ar"
linker = "/Users/j/Desktop/SDKs/android/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi28-clang"

[target.i686-linux-android]
ar = "/Users/j/Desktop/SDKs/android/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/i686-linux-android-ar"
linker = "/Users/j/Desktop/SDKs/android/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/i686-linux-android28-clang"
`
and the files referred to are in the locations specified.
I have consistently cross compiled rust projects without rusqlite to these platforms using these settings unchanged.

in an attempt to hack around this before creating an issue about it, I copied aarch64-linux-android28-clang to aarch64-linux-android-clang and made it available on my path but it still gives this error:

Internal error occurred: Failed to find tool. Is `aarch64-linux-android-clang` installed?

the ios-universal target works as expected, and it would really be a huge bonus to me to be able to use rusqlite with flutter as I am leaning heavily on a rusty-flutter type framework for mobile and desktop app development now.

**Comment by thomcc** [comment]
When we still used bundled on android (at the moment we use sqlcipher which we build manually) in https://github.com/mozilla/application-services I think we worked around this by just adding the relevant toolchain bin dir to our path.

That said, we're using standalone toolchains for various reasons, the prebuilt ones have always been problematic for us (although we haven't tried recently).

**Comment by smokytheangel0** [comment]
thanks for the info, is there a binding in rust that builds well? As far as I can tell the current NDK tools are 'standalone', I feel like my issue might be related to the build process of libsqlite-sys, in that it seems to ignore the ~/.cargo/config I have been using. I tried to find where a string like 'aarch64-linux-android-clang' might be hardcoded from the panic point in the crate 'cc' but I did not have much luck, that said I have alot to learn about sorting things out from a back trace. Speaking of which:

', /Users/j/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.32/src/lib.rs:2367:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: std::panicking::begin_panic_fmt
   7: cc::fail
   8: cc::Build::compile
   9: build_script_build::build::main
  10: build_script_build::main
  11: std::rt::lang_start::{{closure}}
  12: std::panicking::try::do_call
  13: __rust_maybe_catch_panic
  14: std::rt::lang_start_internal
  15: main

**Comment by smokytheangel0** [comment]
I feel like I should include the extra information just for completeness:

error: failed to run custom build command for `libsqlite3-sys v0.13.0`
process didn't exit successfully: `/Users/j/Desktop/Code/rusty_flutter/rust/target/release/build/libsqlite3-sys-46b3ed3ab49141d1/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("aarch64-linux-android")
OPT_LEVEL = Some("3")
HOST = Some("x86_64-apple-darwin")
CC_aarch64-linux-android = None
CC_aarch64_linux_android = None
TARGET_CC = None
CC = None
CFLAGS_aarch64-linux-android = None
CFLAGS_aarch64_linux_android = None
TARGET_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("false")
running: "aarch64-linux-android-clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=aarch64-linux-android" "-Wall" "-Wextra" "-DSQLITE_CORE" "-DSQLITE_DEFAULT_FOREIGN_KEYS=1" "-DSQLITE_ENABLE_API_ARMOR" "-DSQLITE_ENABLE_COLUMN_METADATA" "-DSQLITE_ENABLE_DBSTAT_VTAB" "-DSQLITE_ENABLE_FTS3" "-DSQLITE_ENABLE_FTS3_PARENTHESIS" "-DSQLITE_ENABLE_FTS5" "-DSQLITE_ENABLE_JSON1" "-DSQLITE_ENABLE_LOAD_EXTENSION=1" "-DSQLITE_ENABLE_MEMORY_MANAGEMENT" "-DSQLITE_ENABLE_RTREE" "-DSQLITE_ENABLE_STAT2" "-DSQLITE_ENABLE_STAT4" "-DSQLITE_HAVE_ISNAN" "-DSQLITE_SOUNDEX" "-DSQLITE_THREADSAFE=1" "-DSQLITE_USE_URI" "-DHAVE_USLEEP=1" "-o" "/Users/j/Desktop/Code/rusty_flutter/rust/target/aarch64-linux-android/release/build/libsqlite3-sys-477fd733c75140a1/out/sqlite3/sqlite3.o" "-c" "sqlite3/sqlite3.c"

--- stderr
thread 'main' panicked at '

Internal error occurred: Failed to find tool. Is `aarch64-linux-android-clang` installed?

', /Users/j/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.32/src/lib.rs:2367:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: std::panicking::begin_panic_fmt
   7: cc::fail
   8: cc::Build::compile
   9: build_script_build::build::main
  10: build_script_build::main
  11: std::rt::lang_start::{{closure}}
  12: std::panicking::try::do_call
  13: __rust_maybe_catch_panic
  14: std::rt::lang_start_internal
  15: main

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by thomcc** [comment]
> thanks for the info, is there a binding in rust that builds well? As far as I can tell the current NDK tools are 'standalone', I feel like my issue might be related to the build process of libsqlite-sys, in that it seems to ignore the ~/.cargo/config I have been using. I tried to find where a string like 'aarch64-linux-android-clang' might be hardcoded from the panic point in the crate 'cc' but I did not have much luck, that said I have alot to learn about sorting things out from a back trace. Speaking of which:
> 

I think everything uses libsqlite3-sys (diesel does as well).

Your toolchains look like the prebuilt ones. The standalone toolchains are generated by invoking a python script in `$ndk_root/build/tools/make_standalone_toolchain.py` (they might have taken this out, we're on NDK r15c for various reasons involving older android devices). You can see the scripts we use to set this stuff up https://github.com/mozilla/application-services/blob/master/libs/setup_toolchains_local.sh#L31 (and, to a lesser extent, other scripts in that directory), but again, we don't use the `bundled` rusqlite feature.

If you're extremely patient, we'll probably be looking into this in the next month or two (https://github.com/mozilla/application-services/issues/760) (that said, it's entirely possible we don't hit the same issue, or that we do and work around it by building sqlite separately / manually the way we currently do for sqlcipher).

All that said, it's entirely possible someone who uses the bundled feature has a better fix short term for you. I'm just mentioning what we've done (even though it's only vaguely related) since targeting android isn't too common.

**Comment by smokytheangel0** [comment]
thank you I gather I understand less of this than I read, I will try the standalone and let you know how it worked, though I think it will as that would make this a duplicate of another issue since closed that I thought did not apply since the user didnt use the linux-android##-clang nomenclature. I guess that was the source of mine and libsqlite3-sys' confusion :3.

I hope I am not mistaken in my pursuit of rust as model, flutter as view and controller as it seems a really good combo despite running tests on the targets being a pain I have not sorted out yet. It being niche sounds like there are obvious negatives I am missing to targeting android and ios in this way.

**Comment by smokytheangel0** [comment]
That seems to have done the trick, thank you for your experience. I left the cargo config the same and added the standalone to the path, so hopefully everything that can will go for the NDK built in tools and everything that cant will grab the standalone stuff off the path. I may be overdoctrinated in the update update update ethos though, I feel like there may also be hidden drawbacks to what I've done, feel free to give me your cents. Right now I am just feeling out what rust crates work on ios and android though with an example type program so I can always change it around later.

**Comment by smokytheangel0** [comment]
wow it did not like having the something in between creating the database and table and inserting a single entry, guess I will have to look into returning err strings back into flutter. Sometimes I'm pretty sure rust is the only reason I make myself think I can even program :P.

**Comment by smokytheangel0** [comment]
mobile is alot different from desktop for sure...

**Comment by thomcc** [comment]
I did not hit this when moving https://github.com/mozilla/application-services to use `bundled` builds (in certain cases).

That said, I'm using a standalone toolchain (and not a pregenerated one), and NDK 15c + API version 21, and am using `rust-android-gradle` to perform the build, and it does some magic to make `cc` find everything properly: https://github.com/mozilla/rust-android-gradle/blob/master/plugin/src/main/kotlin/com/nishtahir/CargoBuildTask.kt#L143-L146 (it does this for `cargo` as well, but it's equivalent to the entries in .cargo/config).

**Comment by thomcc** [comment]
We regularly use rusqlite with bundled and other features on android. The way android toolchains are organized (including where Clang would be located) up has also changed considerably since this was filed. Feel free to reopen or file a new issue if you continue to hit this, though.

**Comment by logankeenan** [comment]
I'm still running into the issue that the original poster had and wondering if you all had some suggestions.

* I'm referencing the standalone tool chains created with `make_standalone_toolchain.py`
* I'm using ndk version 21.3.6528147.  Perhaps, that might be related to my issue
* I generated the standalone versions with the following params `--api 26 --arch arm64 --install-dir ~/.NDK/arm64;` which I found by following this [blog](https://visly.app/blog/rust-on-android)
* I'm running `cargo build --target aarch64-linux-android --release` which the same error as the original post.

Any help is appreciated! thank you!

**Comment by logankeenan** [comment]
I was able to figure out my issue. I needed to set my PATH for each compile target in order for libsqlite3 to see them.

Example:
```
export PATH="/Users/logan/.NDK/arm64/bin:$PATH"
export PATH="/Users/logan/.NDK/arm/bin:$PATH"
export PATH="/Users/logan/.NDK/i686/bin:$PATH"
```
