### ISSUE TITLE
Support for UUIDs in FromSql/ToSql

### ISSUE THREAD

**Issue by sbstp** [jgallagher/rusqlite#504]
I'd like to have support for the `uuid` crate and its `Uuid` type in `FromSql`/`ToSql`. It should be behind a feature flag.

If this is something you'd be interested in merging, I can write the PR for it.

**Comment by gwenn** [comment]
SQLite is using Postgresql as a reference implementation.
And `rusqlite` is trying to do the same and use `rust-postgres` as a reference.
`rust-postgres` depends on `uuid` (postgresql supports this datatype natively).
So, yes, let add support to uuid.
