### ISSUE TITLE
FTS5 column filters

### ISSUE THREAD

**Issue by gennaios** [jgallagher/rusqlite#509]
Hello,

I'm trying to use an FTS5 query with [column filters](https://www.sqlite.org/fts5.html#fts5_column_filters). They are specified as:

`... MATCH '"colname" : some text'`
`... MATCH '{col1 col2} : some text'`
`... MATCH '- {col1 col2} : …'`

Is this possible? I get the following error:

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("fts5: syntax error near \":\""))', src/libcore/result.rs:997:5

**Comment by gwenn** [comment]
Could you please provide a simple example (Cargo.toml + main.rs) to reproduce the error ?
Thanks.

**Comment by gwenn** [comment]
Cannot reproduce:
```rust
use rusqlite::{Connection, Result};

fn main() -> Result<()> {
    let db = Connection::open_in_memory()?;

    db.execute_batch(r#"
CREATE VIRTUAL TABLE ft USING fts5(a, b, c);
SELECT * FROM ft WHERE b MATCH 'uvw AND xyz';
SELECT * FROM ft WHERE ft MATCH 'b : (uvw AND xyz)';
SELECT * FROM ft WHERE b MATCH 'a : xyz';
SELECT * FROM ft WHERE b MATCH '"a" : xyz';
SELECT * FROM ft WHERE b MATCH '{a b} : xyz';
SELECT * FROM ft WHERE b MATCH '- {a b} : xyz';
        "#)?;
    Ok(())
}
```

**Comment by gennaios** [comment]
Hello,

thank you for looking into it. It's been a while since I've tried it. I'm also a beginner in Rust. I had tried something like this:

`        let query = "SELECT \
            bookmarks.id, bookmarks.title, bookmarks.section, bookmarks.destination \
            FROM bookmarks \
            JOIN bookmarksindex on bookmarks.id = bookmarksindex.rowid \
            WHERE bookmarks.file_id = :file_id \
            AND bookmarksindex MATCH '{ title section } : :query' ORDER BY 'rank(bookmarksindex)'";

        let mut stmt = self.db.prepare(&query).unwrap();
        let result_rows = stmt.query_map_named(&[(":file_id", &file_id), (":query", &query_string)], |row| Ok(Bookmark {
            id: row.get(0)?,
            title: row.get(1)?,
            section: row.get(2)?,
            destination: row.get(3)?,
        })).unwrap();
`

**Comment by gwenn** [comment]
```sh
$ sqlite3
SQLite version 3.28.0 2019-04-16 19:49:53
sqlite> CREATE TABLE bookmarks (id INTEGER PRIMARY KEY, file_id, title, section, destination);
sqlite> CREATE VIRTUAL TABLE bookmarksindex USING fts5(title, section, content=bookmarks, content_rowid=id);
sqlite> SELECT bookmarks.id, bookmarks.title, bookmarks.section, bookmarks.destination FROM bookmarks JOIN bookmarksindex on bookmarks.id = bookmarksindex.rowid WHERE bookmarks.file_id = :file_id AND bookmarksindex MATCH '{ title section } : :query' ORDER BY 'rank(bookmarksindex)';
Error: fts5: syntax error near ":"
```

**Comment by gwenn** [comment]
Ok,
You must specify `'{title section} : test'` and not just the content to search:
```sh
sqlite> .param set :query '{title section} : test'
sqlite> .param set :file_id 1
sqlite> SELECT bookmarks.id, bookmarks.title, bookmarks.section, bookmarks.destination FROM bookmarks JOIN bookmarksindex on bookmarks.id = bookmarksindex.rowid WHERE bookmarks.file_id = :file_id AND bookmarksindex MATCH :query ORDER BY 'rank(bookmarksindex)';
```

**Comment by gennaios** [comment]
I see. I wasn't aware that's how it worked. I had thought rusqlite was interpolating the string before sending to SQLite. Now understand. Thank you. I will try it. May later have some syntax questions if you don't mind. Besides learning how to use rusqlite, I am also going through the typical issues with learning Rust. Thanks for this wonderful library.

**Comment by gennaios** [comment]
tried it; works wonderfully. thank you.
