### ISSUE TITLE
example code

### ISSUE THREAD

**Issue by benjyz** [jgallagher/rusqlite#518]
running in the example code in the readme with rustc 1.34.1 produces errors for me

```
`error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `std::ops::Try`)`

^ cannot use the `?` operator in a function that returns `()`

```

**Comment by gwenn** [comment]
Are you sure ?
Because [CI](https://travis-ci.org/jgallagher/rusqlite/jobs/525571503#L823) seems ok.
What `rusqlite` version ?
And full error message ?

**Comment by benjyz** [comment]
got it now, the example uses the create time, so I added to cargo `time = "0.1"` and in the code `extern crate time;`
