### ISSUE TITLE
"impl ToSql for NaiveDateTime" documentation is slightly inconsistent with behavior

### ISSUE THREAD

**Issue by muyiliqing** [jgallagher/rusqlite#519]
The comment says` YYYY-MM-DD HH:MM:SS.SSS`, with a space between date and time, while the implementation is `%Y-%m-%dT%H:%M:%S%.f`, with a "T" in the middle.

See code [here](https://github.com/jgallagher/rusqlite/blob/584d94dcf67dad39e95dff4a03684095c544bc58/src/types/chrono.rs#L58).

**Comment by gwenn** [comment]
Indeed,
The comment was originally [ok](https://github.com/jgallagher/rusqlite/blame/42bc173009082eb403089970b72a4a26ad3e5173/src/types/chrono.rs#L72)...
Thanks.

**Comment by gwenn** [comment]
Should be fixed in version 0.19
