### ISSUE TITLE
Add `query_row_named`

### ISSUE THREAD

**Issue by MarkMcCaskey** [jgallagher/rusqlite#528]
Hello!

It'd be nice to be able to use the convenience of `query_row` with the readability of using named parameters.

Additional clarification: as `query` is to `query_named`, `query_row` is to this function.

Thanks for your work on this project!

**Comment by gwenn** [comment]
Add `query_row_named` for prepared `Statement`.

**Comment by MarkMcCaskey** [comment]
Thanks!!
