### ISSUE TITLE
Example documentation for use with files

### ISSUE THREAD

**Issue by evitalis** [jgallagher/rusqlite#529]
I don't mind working on this but it might take me a bit of time, so opening the issue in case someone else gets to it first.

Would it be possible to get an example documented for working with SQLite files rather than in memory only? Feel free to let me know if I am missing something already in place.

**Comment by gwenn** [comment]
https://docs.rs/rusqlite/0.18.0/rusqlite/struct.Connection.html#method.open
+
https://doc.rust-lang.org/nightly/std/path/struct.Path.html

**Comment by evitalis** [comment]
@gwenn I meant getting it added to the example in the Readme or as a working example in an `examples/` in the repo so it is more clear.
