### ISSUE TITLE
Memory leak when using Statement.expanded_sql

### ISSUE THREAD

**Issue by a9y** [jgallagher/rusqlite#552]
The string returned by `sqlite3_expanded_sql` allocates memory but the Statement (and RawStatement) interface makes no attempt to free it.

**Comment by gwenn** [comment]
http://sqlite.org/c3ref/expanded_sql.html
> The string returned by sqlite3_expanded_sql(P), on the other hand, is obtained from sqlite3_malloc() and must be free by the application by passing it to sqlite3_free().

**Comment by gwenn** [comment]
Fixed in 0.21
