### ISSUE TITLE
There's no From for FromSqlError to Error

### ISSUE THREAD

**Issue by kornelski** [jgallagher/rusqlite#555]
`query_map` expects to return `rusqlite::Error`, but `ValueRef` returns `FromSqlError`. Because of that, the convenient syntax `.as_str()?` can't be used in the closure. I'd expect these to work nicely together.

**Comment by gwenn** [comment]
You should use [`get`](https://docs.rs/rusqlite/*/rusqlite/struct.Row.html#method.get) instead of [`get_raw_checked`](https://docs.rs/rusqlite/*/rusqlite/struct.Row.html#method.get_raw_checked).
But if you can't, I will add `impl From< FromSqlError> for rusqlite::error::Error`

**Comment by thomcc** [comment]
In practice this is pretty annoying. I've hit it with the get_raw method on Context. I think I had a reason I didn't implement it when I added the get_raw_blah methods, but sadly I don't remember. I think a straightforward translation too Error was not possible, or something.

**Comment by kornelski** [comment]
I'm using `get_raw(0).as_str()`, because this can be used in an expression, without need to type-hint.

I can't do `match row.get(0) {"foo" => {}}`, for example. I presume `get_raw` also doesn't need to copy the data.

I'd appreciate a `From` implementation.

**Comment by gwenn** [comment]
A PR is welcomed.
Thanks.

**Comment by gwenn** [comment]
Fixed in 0.21
