### ISSUE TITLE
[utf8] Get value from ValueRef::Text as bytes

### ISSUE THREAD

**Issue by Jikstra** [jgallagher/rusqlite#561]
I currently have the problem that I sometimes have non utf8 text in the database, so every call to convert it into valid utf8 fails. ValueRef stores text since 0.20 as `&'a [u8]` but we only can get it out of that datastructure as &str, during the conversion to an &str rusqlite expects the value to be valid utf8, there's no public method to get it as it is.
I propose implementing an `as_str_raw` method which does something like this:
```
    /// If `self` is case `Text`, returns the raw string value. Otherwise, returns
    /// `Err(Error::InvalidColumnType)`.
    pub fn as_str_raw(&self) -> FromSqlResult<&'a [u8]> {
        match *self {
            ValueRef::Text(t) => {
                t
            }
            _ => Err(FromSqlError::InvalidType),
        }
    }
```

I could do a pr for this in case this makes sense and I don't oversee anything. 

EDIT: Getting it as a lossy utf8 string could also be helpful, that's what I want to achieve in the end.

**Comment by gwenn** [comment]
See #548

**Comment by gwenn** [comment]
Use [`get_raw`](https://docs.rs/rusqlite/0.20.0/rusqlite/struct.Row.html#method.get_raw) ?
```rs
match row.get_raw(0) {
    ValueRef::Text(t) => {
        t
    }
    _ => ...
}

```

**Comment by Jikstra** [comment]
Don't understand that rust magic yet but this works. Thanks :)
