### ISSUE TITLE
Error occurs on using OpenFlags::SQLITE_OPEN_READ_WRITE

### ISSUE THREAD

**Issue by mohankumaranna** [jgallagher/rusqlite#562]
On trying to use `OpenFlags::SQLITE_OPEN_READ_WRITE`, an error occurs that says: **SqliteFailure(Error { code: APIMisuse, extended_code: 21 }, None)**.

My code is:
`fn open_connection() -> Result<Connection> {
    println!("Opening database connection...");
    Connection::open_with_flags( path(), OpenFlags::SQLITE_OPEN_READ_WRITE )
}`
In the Sqlite document, this flag is mentioned as SQLITE_OPEN_READWRITE ( _ is missing between READWRITE); not sure, this is the cause.

If the code is used with no flag such as:  `Connection::open( path() )`, there is no error; but I want to use flag so as to separate create db and open db.  

Thanks,
Mohan

**Comment by gwenn** [comment]
Could you please provide a complete example to reproduce this issue ?
I have just updated this [test](https://github.com/jgallagher/rusqlite/blob/master/src/lib.rs#L893) to make sure everything is fine.

**Comment by mohankumaranna** [comment]
I already refactored my code to use different approach.  After seeing your response, I tried to rebuild it with old style, but I am unable to reproduce the exact error.  So, you may please close this issue.  Thanks for your time.
