### ISSUE TITLE
`execute()` may return stale number of changed rows

### ISSUE THREAD

**Issue by fzgregor** [jgallagher/rusqlite#565]
Using `execute()` with a select query returns the number of rows changed in the last database altering query. It would be better to return 0.

I have a select query for which I'm only interested in the number of returned rows. https://docs.rs/diesel/1.4.2/diesel/query_dsl/trait.RunQueryDsl.html#method.execute only spoke about returning the number of "affected rows". Though the description still made me wonder whether it is the correct function to use. After testing, everything seemed to work as expected (due to the above issue of returning a stale number of changed rows from a previous insert). Now I spent way too long to figure out what was wrong with the application.

`rusqlite` could use https://www.sqlite.org/c3ref/total_changes.html before and after the query instead of `sqlite3_changes` to prevent the return of a stale number of affected rows.

**Comment by gwenn** [comment]
We can check that [sqlite3_column_count](http://sqlite.org/c3ref/column_count.html) returns 0. But it doesn't work with some PRAGMA.
We can also check that [sqlite3_stmt_readonly](http://sqlite.org/c3ref/stmt_readonly.html) returns false.
There is already a check [here](https://github.com/jgallagher/rusqlite/blob/4db226c0dfb8cf2250f451e525ab24c4b9bb97d2/src/statement.rs#L524). But it does not work if your SELECT returns nothing.
