### ISSUE TITLE
Readme code produces warnings

### ISSUE THREAD

**Issue by sirxyzzy** [jgallagher/rusqlite#586]
When I copy pasted the code from the readme, I got a  warning, to fix the code I had to add "dyn" , maybe this is a feature?

`    conn.execute(
        "INSERT INTO person (name, time_created, data)
                  VALUES (?1, ?2, ?3)",
        &[&me.name as &dyn ToSql, &me.time_created, &me.data],
    )?;`

The warning was

  ```
 trait objects without an explicit `dyn` are deprecated
   note: `#[warn(bare_trait_objects)]` on by default
   help: use `dyn`: `dyn ToSql`rustc(bare_trait_objects)

```

**Comment by gwenn** [comment]
Sorry,
Example has been updated: [params](https://docs.rs/rusqlite/*/rusqlite/macro.params.html) macro should be used.
