### ISSUE TITLE
Query with LIKE operator and pattern matching

### ISSUE THREAD

**Issue by Rudo2204** [jgallagher/rusqlite#600]
I'm trying to query this statement with rusqlite:
```sqlite
select id, name from student where name like %ali%
```
I tried the following
```rust
let mut stmt = conn.prepare("select id, name from student where name like %(?)%")?;
```
but it returns this error: `near "%": syntax error`
Right now I can make it work by removing those percent signs and use `params![format!("%{}%", name)]` instead.However, this is quite an ugly solution... 
Is there any built-in function of rusqlite to overcome this?
If there is not, you can just reply so and close this issue. Thanks for your time!

**Comment by gwenn** [comment]
Not related to `rusqlite`
You mean:
```
"select id, name from student where name like '%' || ? || '%'"
```
See #573

**Comment by gwenn** [comment]
```
sqlite> .parameter init
sqlite> .parameter set ?1 is
sqlite> CREATE TABLE student AS SELECT 1 AS id, 'bart' AS name UNION SELECT 2, 'lisa';
sqlite> SELECT id, name FROM student WHERE name LIKE '%' || ? || '%';
2|lisa
```

**Comment by Rudo2204** [comment]
Thanks you. That was exactly what I was looking for. I'm closing this issue now.
