### ISSUE TITLE
Feature Request: another, more flexible way of getting values from Row

### ISSUE THREAD

**Issue by billop** [jgallagher/rusqlite#605]
I wish there was a method perhaps called `get_all_lossy` for Row which would return a map where the keys are columns and values are values turned into strings (or perhaps maintaining appropriate type but that would be much more complicated).

An upside of such a method would be that it could be used to implement Debug/Display for Row.

I work with unknown schemas and it seems to me that at the moment there's no way to really extract everything from a `SELECT * FROM table` query without hardcoding everything, including types.

**Comment by billop** [comment]
Made a draft PR here: https://github.com/jgallagher/rusqlite/pull/606

**Comment by gwenn** [comment]
What's wrong/missing with [Value](https://github.com/jgallagher/rusqlite/blob/bb3db3f877a3e8a5785d9ea5e4ae4cca0ffe46d7/src/types/mod.rs#L339) ?

**Comment by billop** [comment]
Oh! That's much better. Sorry, didn't realize that existed. Should Value also be used to Impl Debug for Row do you think?

**Comment by gwenn** [comment]
Definitely. But we have to be careful in case there is a 1 Gb Blob...
Either print only some bytes or by default, dump only the blob size not its content ?
