### ISSUE TITLE
rarray not working

### ISSUE THREAD

**Issue by juancampa** [jgallagher/rusqlite#607]
First of all, thanks for the amazing library.

I'm trying to use `rarray` but it doesn't seem to work:

```
let mut stmt = conn.prepare_cached("SELECT * FROM mytable WHERE seq IN rarray(?)")?;
```
But I get this error:
```
SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("no such table: rarray"))
```
I have this in my `Cargo.toml` which I believe is the only requirement to make it work
```
[dependencies.rusqlite]
version = "0.21"
features = ["bundled", "vtab", "array" ]
```

Is there anything else I need to enable to get support for `rarray` working?

**Comment by gwenn** [comment]
Without a complete example, my guess is that you are missing a [`load_module`](https://github.com/jgallagher/rusqlite/blob/master/src/vtab/array.rs#L180).

**Comment by juancampa** [comment]
Thanks @gwenn, that was one of the issues, the other one being that the array must be wrapped in an `Rc` [to get the `ToSql` impl](https://github.com/jgallagher/rusqlite/blob/cb6f890e48b6f42ddc6169d471d8f7c168888c35/src/vtab/array.rs#L24).

It works now!
