### ISSUE TITLE
`bundled` feature should be split into two features

### ISSUE THREAD

**Issue by thomcc** [jgallagher/rusqlite#612]
The bundled feature does a couple things:

1. Causes the build to include the bundled sqlite.
2. Disables certain checks that are irrelevant if we're using the bundled sqlite, mostly around versions, but I haven't done an exhaustive study here.
3. Causes rusqlite to assume it's using a modern version of sqlite, and lets it expose a number of features (among other things).

There are a lot of cases where someone might want the third part enabled, but not the first two.

I think adding a new feature, `modern-sqlite` which just turned those things on, without enabling bundling, would be good. Then `bundled` would depend on it, and most of the `#[cfg(feature = "bundled")]` inside Rusqlite would chage to `#[cfg(feature = "modern-sqlite")]`.  (Cases where the check is actually only relevant for bundling would stay the same -- for example, the places rusqlite bypasses version checks based on `bundled` should stay the way they are).

I think this applies only to `rusqlite` and not `libsqlite3-sys`, but I could be forgetting something.

**Comment by gwenn** [comment]
I agree and I will check `libsqlite3-sys`.
