### ISSUE TITLE
params![] for more than 32 values

### ISSUE THREAD

**Issue by MrTanoshii** [jgallagher/rusqlite#614]
My table has 34 columns (included the UNIQUE id), I have problems with INSERT as whenever I try to insert all 33 values (id is excluded), I get a compile error which I believe is due to a limit in the number of values sent in a single .execute() with params![values, ..., values]

My question is, is there a safe way to increase the limit of values processed?

Note: SELECT has no problem retrieving all 34 columns.

**Comment by gwenn** [comment]
I cannot reproduce:
```rust
        #[test]
        fn test_params() {
            let db = checked_memory_handle();
            let ones = ::std::iter::repeat(1).take(34);
            db.query_row("SELECT ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?;", ones, |r| {
                assert_eq!(1, r.get_unwrap::<_, i32>(0));
                Ok(())
            }).unwrap();
        }
```
Could you please provide the error ?

**Comment by thomcc** [comment]
I can repro -- it's an issue with the `params!` macro:

```rust
    let db = rusqlite::Connection::open_in_memory().unwrap();
    db.query_row("SELECT 
            ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
            ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
            ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
            ?, ?, ?, ?, ?, ?;", 
        rusqlite::params![
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
            1, 1, 1, 1, 1, 1,
        ] as &[&dyn rusqlite::ToSql],
        |r| {
            assert_eq!(1, r.get_unwrap::<_, i32>(0));
            Ok(())
        }
    ).unwrap();
```
fails because it exceeds https://doc.rust-lang.org/std/array/trait.LengthAtMost32.html, and so &[T; N] is no longer IntoIterator, I think.

If you hit this you can work around it with `rusqlite::params![...] as &[&dyn rusqlite::ToSql]` for now.

**Comment by MrTanoshii** [comment]
`error[E0277]: the trait bound '&[&dyn rusqlite::types::to_sql::ToSql; 33]: std::iter::IntoIterator' is not satisfied
   --> src\bin\add_entries.rs:84:3
    |
84  |           params![entry.date,
    |  _________^
85  | |             entry.ac_type,
86  | |             entry.reg,
87  | |             entry.pic,
...   |
115 | |             entry.rmks,
116 | |             entry.x_country]
    | |____________________________^ the trait 'std::iter::IntoIterator' is not implemented for '&[&dyn rusqlite::types::to_sql::ToSql; 33]'`

Indeed, the error is as thomcc provided

**Comment by thomcc** [comment]
This as been fixed for a while.
