### ISSUE TITLE
query_row finds a row while query_map with prepare not retrieving any rows

### ISSUE THREAD

**Issue by FanOfSilence** [jgallagher/rusqlite#615]
I have a pretty simple example where I have a few rows in a table, and I'm able to see the rows in a cli and by using _query_row_ but when trying to use _query_map_ with a _prepare_ statement I'm getting nothing.

```
       let sql = format!("SELECT * FROM {}", table_name);
        let row: T = self
            .connection
            .query_row(&sql, NO_PARAMS, |row| {
                let one: Key = row.get(0).expect("one");
                let two: T = row.get(1).expect("two");
                let three: String = row.get(2).expect("three");
                let four: Instance = row.get(3).expect("four");
                println!("row {:?}, {:?}, {:?}, {:?}", one, two, three, four);
                row.get(0)
            })
            .unwrap();

        let mut stmt = self.connection.prepare(&sql)?;
        stmt.query_map(NO_PARAMS, |row| {
            println!("got row!",);
            Ok(())
        })?;
```

The first print shows the row I'm expecting, while "got row!" is never printed. I have gotten an example to work without generics and using _query_map_. Seems unlikely but might that be the reason?
I'm using rusqlite 0.21.0 with the _bundled_ feature. I'm using file storage.

**Comment by gwenn** [comment]
`query_map` returns an iterator.
If you don't use the iterator, you print nothing.

**Comment by FanOfSilence** [comment]
Ah yes, in the example the iterator was consumed but I removed those lines... Thanks!
