### ISSUE TITLE
Unclear usage of "time" in README example

### ISSUE THREAD

**Issue by dbr** [jgallagher/rusqlite#625]
Minor thing - I copypasted the code from the README to begin playing with the library, and got an error

```
error[E0432]: unresolved import `time`
 --> src/db.rs:2:5
  |
2 | use time::Timespec;
  |     ^^^^ help: a similar path exists: `std::time`
```

It took a tiny bit of poking around to work out it was a thirdparty requirement (mostly as searching for "rust time" is a bit messy)

Not sure if the `std::time` could be used without cluttering up the example - but possibly just a comment on that line or similar would handy?

```rust
use time::Timespec; # https://crates.io/crates/time
```

**Comment by sigod** [comment]
Also, it should be noted, that `time` v0.1.* must be used, because `Timespec` was removed in v0.2.0.

**Comment by jhpratt** [comment]
Maintainer of the time crate here. I can help with a PR if anyone wants to support 0.2! Feel free to ping me and/or join Matrix (link at [time-rs/time](https://github.com/time-rs/time)).

**Comment by thomcc** [comment]
I looked into this a little. I'm concerned about not being able to parse exiting timestamps, or common ones generated by sqlite (https://www.sqlite.org/lang_datefunc.html): https://github.com/time-rs/time/issues/232. That said, I guess maybe that code we have doesn't even work as is? I don't know... 

Also, I think we probably should have this behind a feature the way with other crate support, but maybe on by default for compatibility.

**Comment by gwenn** [comment]
A feature like [rust-postgres](https://github.com/sfackler/rust-postgres) would be nice.

**Comment by steadylearner** [comment]
[I made an example with chrono to use timestamp.](https://github.com/steadylearner/Rust-Full-Stack/blob/master/database/sqlite_rust/src/main.rs)

Use it instead of the current example.

**Comment by ngirard** [comment]
Hey folks,

while contributing to a small free software project I got stuck while trying to update the `time` crate from 0.1 to 0.2.
On the `time` crate side, the information is very sparse -- no upgrading instructions associated to the [0.2 release](https://github.com/time-rs/time/releases/tag/v0.2.0), and no clear guidance in the [associated issue](https://github.com/time-rs/time/issues/190).
I'd be grateful if @jhpratt could help with a PR as proposed.

Cheers & take care !

PS: I see you [removed](https://github.com/rusqlite/rusqlite/pull/654) the use of `time` in the README (hopefully it's temporary), but the removal didn't make its way to [docs.rs](https://docs.rs/rusqlite/0.22.0/rusqlite/).

**Comment by jhpratt** [comment]
@ngirard If anyone wants to start a PR, I'll happily help when I have time. I can't manage doing it all myself, time-wise.

**Comment by thomcc** [comment]
https://github.com/rusqlite/rusqlite/issues/653

I have a half-finished PR for this on my work computer, but it's waiting for a release of `time` that has the parsing/formatting additions mentioned in https://github.com/time-rs/time/issues/232.

**Comment by jhpratt** [comment]
@thomcc I was actually planning on a release that includes that later tonight :slightly_smiling_face:

**Comment by crazcalm** [comment]
Heads up, the README on crates.io still has the `Timespec` version. When y'all have a chance, would you mind updating crates.io?

**Comment by thomcc** [comment]
@crazcalm Doesn't appear to: https://crates.io/crates/rusqlite...

**Comment by crazcalm** [comment]
@thomcc Sorry for the confusion. It is on this page: https://docs.rs/rusqlite/0.23.1/rusqlite/
