### ISSUE TITLE
Multiple params ???

### ISSUE THREAD

**Issue by zero-systems** [jgallagher/rusqlite#661]
I have a big expression with a lot of where in params.
How can I bind param and add another with different type?

I tried `params! { arr, another }` -- not working (and Vec<T> does not implement ToSql)
Everything I can is to recreate array or chain two iterators with same type.

Is there any solution?

**Comment by zero-systems** [comment]
It would be also cool to add support for `(A, B)` where both are different types and implement ToSql.
(And do this for same type too, I don't see any impls).

**Comment by gwenn** [comment]
https://sqlite.org/carray.html
https://github.com/jgallagher/rusqlite/blob/master/Cargo.toml#L49

**Comment by zero-systems** [comment]
Thanks for your help!

Anyway, I can't compile rusqlite with feature `array` because it needs feature 'modern_sqlite'. I think it should be included in dependency for `array`.

**Comment by thomcc** [comment]
It's somewhat deliberate that we don't turn on modern_sqlite automatically -- it means that you have the same version (or newer) of sqlite that we bundle which is very easy to mix up. I don't think we should turn it on automatically.

**Comment by zero-systems** [comment]
I see that Array impls to sql, what it actually generates? What should I pass to carray function?

**Comment by thomcc** [comment]
See https://github.com/jgallagher/rusqlite/blob/master/src/vtab/array.rs#L178-L197 -- it's actually rarray for rust. It behaves as a table.

**Comment by zero-systems** [comment]
Thanks!
