### ISSUE TITLE
Add ability to get the column names and number of columns returned in a row.

### ISSUE THREAD

**Issue by ivanceras** [jgallagher/rusqlite#67]
There's no way to extract the values of each column in a row when you don't know what are the columns of the tables. 
use case: generated query from an ORM.
```
select * from sqlite_master;
```
http://jgallagher.github.io/rusqlite/rusqlite/struct.SqliteRow.html
SqliteRow lacks the information of how many columns should i iterate and what are the column names of each.

**Comment by gwenn** [comment]
Maybe
http://jgallagher.github.io/rusqlite/rusqlite/struct.SqliteStatement.html#method.column_names
?

**Comment by ivanceras** [comment]
Oh, i didn't notice its there I expect it to be in the resultset after the query has been executed. So, these also means I can call these before executing the query to fetch data?.

**Comment by gwenn** [comment]
There is no distinction between Statement and ResultSet in SQLite (there is no ResultRet (only Statement) in SQLite)...
And, yes, the column names/count are computed during the preparation/compilation phase, not during the evaluation/execution phase.
Beware that the statement can be recompiled automatically at the beginning of the evaluation if the database schema is changed (for example if a column is added) which may invalidate the column names/count...
