### ISSUE TITLE
Panics when wrong bind arguments provided

### ISSUE THREAD

**Issue by dae** [jgallagher/rusqlite#671]
Currently Rusqlite asserts that the bind parameters are correct:

https://github.com/jgallagher/rusqlite/blob/master/src/statement.rs#L440

I understand the logic here - it's a programming error after all - but this unfortunately is not ideal for my use case. 

I have a Python app with a plugin ecosystem, and which exposes DB access to plugin authors. Recently I switched out the old Python DB API to use Rusqlite under the hood, as part of a move towards using more Rust in the codebase. This mostly works fine - if the add-on author makes a mistake in their SQL, the prepare statement will return a Rusqlite error which I can propagate back to Python. But if they provide SQL that doesn't match the number of arguments, the app crashes.

Would you be interested in accepting a patch that converts this assert to an error instead? If so, please let me know whether you'd like an existing error to be reused, or whether I should create a new one. If not, is there another way it could be solved that you'd be willing to accept?

**Comment by thomcc** [comment]
I was thinking this when I did #668. Making it an error sounds good to me.
