### ISSUE TITLE
params! macro does not support creating tables?

### ISSUE THREAD

**Issue by captchaKing** [jgallagher/rusqlite#709]
This test does not work for me:
#[test]
fn t() {
    let db = Connection::open_in_memory().unwrap();
    db.execute("CREATE TABLE ? (id INTEGER PRIMARY KEY)", params!["admin"]).unwrap();
}
But i can create table using format! macro like this:
    db.prepare(&format!("CREATE TABLE {} (id INTEGER PRIMARY KEY)", "admin")).unwrap()
        .finalize().unwrap();
Is this intended or im using it wrong. Thanks!

**Comment by thomcc** [comment]
No, SQLite (nor any other SQL database I know of) doesn't support this. Generally I'd recommend just writing the table name in rather than using a separate variable.

**Comment by captchaKing** [comment]
I need it to be separate, because DB is gonna be created by dynamically.
Never thought that params! is somehow related to databases, and not just convenience macro for placing parameters in string.
Sorry for disturbing, im newbie in DBes.

**Comment by gwenn** [comment]
You should try to search `sql builder` or `sql generator` on crates.io .
Or use the AST from an `sql parser` but it may be cumbersome.
Like https://docs.rs/nom-sql/0.0.11/nom_sql/struct.CreateTableStatement.html.
