### ISSUE TITLE
SqliteConnection::query_row should return formal error type if there is no row to return

### ISSUE THREAD

**Issue by Dashed** [jgallagher/rusqlite#79]
The following error return isn't all that useful: https://github.com/jgallagher/rusqlite/blob/7586556db5b4ad4db94e5e6ab5232f8868b8f5c9/src/lib.rs#L299-L302

And capturing the error through string comparison `message` isn't a good solution.

I think it may be useful to have error types that can be externally captured via rusqlite as a library.

This may require `SqliteError` to be an enum or something.

**Comment by jgallagher** [comment]
@Dashed Continuing with the "better late than never" theme, I have a local branch that does indeed change `SqliteError` to an enum. It sprouted several more cases than I was expecting, where we were (ab)using SQLite error codes for errors occurring on the Rust side. The change is relatively minor but quite widespread, so I'm going to wait for the currently-open PRs to get finished and merged in. This is coming soon though!

**Comment by Dashed** [comment]
Awesome to hear! :+1:  I'm definitely look forward to seeing this on master.

**Comment by jgallagher** [comment]
@Dashed merged into master. Please give it a shot and let me know if there are any issues!
