### ISSUE TITLE
Why the T in query_map, and query_and_then is constrained with 'static?

### ISSUE THREAD

**Issue by krdln** [jgallagher/rusqlite#82]
The `query_map` has a following signature:

```rust
fn query_map<'a, T, F>(&'a mut self, params: &[&ToSql], f: F) -> SqliteResult<MappedRows<'a, F>> 
where T: 'static, F: FnMut(SqliteRow) -> T
```

From my understanding, the `T: 'static` constraint is redundant. What is the reason for it to be there?

**Comment by jgallagher** [comment]
Hmm, yeah, I think you're right. The intent was to make sure the caller couldn't collect the `SqliteRow` handles being passed into the closure; e.g.,

```rust
let rows = query.query_map(&[], |row| row);
```

but even without the `T: 'static` I don't think it's possible to get this to compile. I wonder if a solution to [this open bug](https://github.com/rust-lang/rust/issues/22340) (related to [this SO question](http://stackoverflow.com/questions/28512314/how-do-i-get-lifetime-of-reference-to-owned-object-cannot-infer-an-appropriate) about closures that return references) would make it possible to write this, at which point the `T: 'static` would no longer be redundant. What do you think?

**Comment by krdln** [comment]
Oh, now I see the reason of that `static`. But the worst thing that would happen, if somebody's collected these rows, would be just a panic, nothing more, right?

So if the `'static` were removed, the bug (still not fixed :disappointed:) wouldn't prevent returning rows from a closure (the workarounds a really simple (create standalone `fn` or just don't use annotations)).

But I think there's a way to prevent collecting rows without restricting `T`! I you'd change the `F` type inside `MappedRows` from `FnMut(SqliteRow) -> T` to `FnMut(&SqliteRow) -> T`, Rust would naturally prevent the short-lived reference from escaping the closure body. And since `SqliteRow` is not `Copy`, then no panics guaranteed! (expect of somebody calling `.get(999)` of course.

**Comment by jgallagher** [comment]
> But the worst thing that would happen, if somebody's collected these rows, would be just a panic, nothing more, right?

Correct. And actually just collecting them is fine; it'd just panic if someone tried to _use_ a collected row.

> I you'd change the `F` type inside `MappedRows` from `FnMut(SqliteRow) -> T` to `FnMut(&SqliteRow) -> T`, Rust would naturally prevent the short-lived reference from escaping the closure body.

Ahh, that's a great point. Will make that change shortly.
