### ISSUE TITLE
Consider building SQLite as part of the build process if we can't find it on the system.

### ISSUE THREAD

**Issue by jgallagher** [jgallagher/rusqlite#89]
This is what [libgit2-sys](http://doc.crates.io/build-script.html#case-study-linking-to-system-libraries) does, and was also mentioned as a possible solution to difficulties on Windows in #46.

**Comment by bottiger** [comment]
I would love to see this implemented in a not too distant future.

**Comment by photex** [comment]
I just submitted a PR for sqlite3-src which does this and works on the big 3 at least: https://github.com/stainless-steel/sqlite3-src/pull/1

I'd be happy to submit something similar here after that PR is finished.

**Comment by jgallagher** [comment]
This is now available as the `bundled` feature (see #176 / #197).
